<?php
/**
 * SEO METADATA MAPPING TABLE - PASSION LINK (phache.com.vn)
 * Tối ưu chuẩn SEO Top 1 Google & Entity E-E-A-T 2026.
 * 100% Tiếng Việt có dấu chính xác, văn phong chuyên nghiệp, không lỗi font/không dấu.
 */

function get_seo_metadata_for_current_request($req_uri, $news_id = 0) {
    static $seo_map_cache = null;
    if ($seo_map_cache === null) {
        $seo_map_cache = array(
            '/' => array('id' => 0, 'title' => 'Học Pha Chế Mở Quán Trà Sữa, Cà Phê Chuyên Nghiệp | Passion Link', 'description' => 'Trung tâm dạy pha chế Passion Link tiên phong đào tạo mở quán trà sữa, cà phê, barista chuẩn vị từ 2009. Hơn 3.000+ học viên mở quán thành công. Đăng ký ngay!', 'h1' => 'Học Viện Đào Tạo Pha Chế Trà Sữa, Cà Phê Mở Quán Chuyên Nghiệp Passion Link'),
            '/cac-khoa-hoc-day-pha-che.html' => array('id' => 0, 'title' => 'Các Khóa Học Pha Chế Đồ Uống Mở Quán Chuyên Nghiệp [Menu 2026]', 'description' => 'Tổng hợp các khóa học pha chế trà sữa, cà phê barista, trà trái cây chuẩn vị mở quán tại Passion Link. Cam kết 100% thực hành thực tế. Xem lịch học ngay!', 'h1' => 'Tổng Hợp Các Khóa Học Dạy Pha Chế Chuyên Nghiệp Mở Quán Thành Công'),
            '/day-pha-che-tra-sua-ngon.html' => array('id' => 0, 'title' => 'Dạy Pha Chế Trà Sữa Ngon Mở Quán: Bí Quyết Độc Quyền [2026]', 'description' => 'Hướng dẫn bí quyết dạy pha chế trà sữa ngon chuẩn vị mở quán: ủ trà đậm vị, làm trân châu dẻo, kem cheese béo ngậy. Đăng ký nhận giáo trình độc quyền ngay!', 'h1' => 'Cẩm Nang Dạy Pha Chế Trà Sữa Ngon & Bí Quyết Mở Quán Trà Sữa Đắt Khách'),
            '/lich-khai-giang.html' => array('id' => 0, 'title' => 'Lịch Khai Giảng Các Khóa Học Pha Chế Mới Nhất [Tháng Này]', 'description' => 'Cập nhật lịch khai giảng các khóa học pha chế trà sữa, barista, trà trái cây tại TP.HCM, Hà Nội, Cần Thơ, Đà Nẵng. Ưu đãi đăng ký sớm, xem ngay!', 'h1' => 'Lịch Khai Giảng Lớp Học Pha Chế Tại TP.HCM, Hà Nội, Đà Nẵng & Cần Thơ'),
            '/mo-quan.html' => array('id' => 0, 'title' => 'Cẩm Nang Mở Quán Trà Sữa, Cà Phê Từ A-Z: Chi Phí & Vận Hành [2026]', 'description' => 'Tư vấn mở quán trà sữa cà phê trọn gói từ Passion Link: Lập kế hoạch tài chính, chọn mặt bằng, mua máy móc quầy bar, lên menu hút khách. Xem chi tiết!', 'h1' => 'Tư Vấn & Hướng Dẫn Kinh Nghiệm Mở Quán Trà Sữa, Cà Phê Thành Công'),
            '/he-thong-chi-nhanh.html' => array('id' => 0, 'title' => 'Hệ Thống 4 Chi Nhánh Đào Tạo Pha Chế Passion Link Toàn Quốc [2026]', 'description' => 'Hệ thống cơ sở đào tạo pha chế Passion Link tại TP.HCM (Quận 10, Phú Nhuận), Hà Nội, Cần Thơ. Phòng thực hành quầy bar hiện đại, đăng ký ngay!', 'h1' => 'Hệ Thống Cơ Sở & Chi Nhánh Học Viện Pha Chế Passion Link'),
            '/passion-link-lich-su-phat-trien.html' => array('id' => 0, 'title' => 'Lịch Sử Phát Triển Passion Link: 17+ Năm Tiên Phong Đào Tạo Pha Chế', 'description' => 'Hành trình hơn 17 năm tiên phong đào tạo pha chế đồ uống mở quán của Passion Link: Sứ mệnh nâng tầm chất lượng đồ uống Việt Nam và kiến tạo chủ quán thành công.', 'h1' => 'Lịch Sử Hình Thành & Sứ Mệnh Tiên Phong Đào Tạo F&B Passion Link'),
            '/chinh-sach-thanh-toan-hoan-coc.html' => array('id' => 0, 'title' => 'Chính Sách Thanh Toán & Hoàn Cọc Khóa Học | Passion Link', 'description' => 'Quy định chi tiết về chính sách thanh toán học phí, chính sách bảo lưu và điều kiện hoàn cọc khóa học tại Học viện Đào tạo Pha chế Passion Link.', 'h1' => 'Chính Sách Học Phí, Bảo Lưu & Hoàn Cọc Khóa Học Passion Link'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-cat-tia-trai-cay-trang-tri-62.html' => array('id' => 62, 'title' => 'Khóa Học Cắt Tỉa Trái Cây Trang Trí Đồ Uống [Menu 2026]', 'description' => 'Khóa học dạy cắt tỉa trái cây trang trí đồ uống quầy bar chuyên nghiệp tại Passion Link: Kỹ thuật tạo hình đẹp mắt, nâng tầm giá trị ly đồ uống kinh doanh.', 'h1' => 'Khóa Học Dạy Cắt Tỉa Trái Cây Trang Trí Đồ Uống Mở Quán Chuyên Nghiệp'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-cat-tia-trai-cay-trang-tri-nuoc-uong-62.html' => array('id' => 62, 'title' => 'Khóa Học Cắt Tỉa Trái Cây Trang Trí Đồ Uống [Menu 2026]', 'description' => 'Khóa học dạy cắt tỉa trái cây trang trí đồ uống quầy bar chuyên nghiệp tại Passion Link: Kỹ thuật tạo hình đẹp mắt, nâng tầm giá trị ly đồ uống kinh doanh.', 'h1' => 'Khóa Học Dạy Cắt Tỉa Trái Cây Trang Trí Đồ Uống Mở Quán Chuyên Nghiệp'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-lam-bingsu-ngon-de-mo-quan-cao-cap-theo-cong-nghe-han-quoc-100.html' => array('id' => 100, 'title' => 'Khóa Học Làm Bingsu Hàn Quốc Chuẩn Vị Mở Quán [Menu 2026]', 'description' => 'Khóa học làm Bingsu tuyết Hàn Quốc cao cấp mở quán tại Passion Link: Công nghệ bào tuyết mềm mịn, kỹ thuật phối sốt và trang trí topping độc quyền.', 'h1' => 'Khóa Học Dạy Làm Bingsu Hàn Quốc Chuẩn Vị Mở Quán Cao Cấp'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-lam-kem-ngon-63.html' => array('id' => 63, 'title' => 'Khóa Học Làm Kem Ngon Mở Quán Kinh Doanh [Menu 2026]', 'description' => 'Khóa học làm kem ngon mở quán tại Passion Link: Nắm vững bí quyết làm kem từ các thương hiệu kem nổi tiếng thế giới, công thức chuẩn xốp dẻo thơm ngậy.', 'h1' => 'Khóa Học Dạy Làm Kem Ngon - Bí Quyết Từ Thương Hiệu Kem Nổi Tiếng'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-lam-kem-ngon-by-quyet-tu-cac-thuong-hieu-kem-noi-tieng-63.html' => array('id' => 63, 'title' => 'Khóa Học Làm Kem Ngon Mở Quán Kinh Doanh [Menu 2026]', 'description' => 'Khóa học làm kem ngon mở quán tại Passion Link: Nắm vững bí quyết làm kem từ các thương hiệu kem nổi tiếng thế giới, công thức chuẩn xốp dẻo thơm ngậy.', 'h1' => 'Khóa Học Dạy Làm Kem Ngon - Bí Quyết Từ Thương Hiệu Kem Nổi Tiếng'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-lam-tau-hu-thai-mon-ngon-bi-truyen-87.html' => array('id' => 87, 'title' => 'Khóa Học Làm Tàu Hủ Thái Ngon Chuẩn Vị [Menu 2026]', 'description' => 'Khóa học làm tàu hủ Thái thơm ngon chuẩn vị tại Passion Link: Bí quyết nấu tàu hủ dẻo mịn béo ngậy, kết hợp sốt trân châu và thạch độc quyền hút khách.', 'h1' => 'Khóa Học Dạy Làm Tàu Hủ Thái Ngon - Công Thức Bí Truyền Passion Link'),
            '/cac-khoa-hoc-day-pha-che/day-hoc-cach-lam-thach-cu-nang-thach-cu-mon-thach-khuc-bach-thach-pho-mai-hat-tran-chau-99.html' => array('id' => 99, 'title' => 'Khóa Học Làm Thạch Trà Sữa & Trân Châu Tươi [Menu 2026]', 'description' => 'Khóa học làm các loại thạch trà sữa và trân châu tươi màu rau củ tại Passion Link: Thạch củ năng, củ môn, khúc bạch, phô mai và trân châu dẻo dai tự làm.', 'h1' => 'Khóa Học Dạy Làm Thạch Trà Sữa Các Loại & Trân Châu Nhà Làm Tươi Ngon'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-cafe-da-xay-kem-cafe-take-away-smoothies-kem-barista-chuyen-nghiep-37.html' => array('id' => 37, 'title' => 'Khóa Học Pha Chế Cà Phê Đá Xay Kem & Barista Take Away [Menu 2026]', 'description' => 'Khóa học pha chế cà phê đá xay kem, smoothies và cà phê take away tại Passion Link: Thực hành 100% trên máy pha chuyên nghiệp, hỗ trợ lên menu mở quán.', 'h1' => 'Khóa Học Dạy Pha Chế Cà Phê Đá Xay Kem, Take Away & Smoothies Barista Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-cafe-take-away-bartender-37.html' => array('id' => 37, 'title' => 'Khóa Học Pha Chế Cà Phê Đá Xay Kem & Barista Take Away [Menu 2026]', 'description' => 'Khóa học pha chế cà phê đá xay kem, smoothies và cà phê take away tại Passion Link: Thực hành 100% trên máy pha chuyên nghiệp, hỗ trợ lên menu mở quán.', 'h1' => 'Khóa Học Dạy Pha Chế Cà Phê Đá Xay Kem, Take Away & Smoothies Barista Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-cafe-take-away-smoothies-bartender-37.html' => array('id' => 37, 'title' => 'Khóa Học Pha Chế Cà Phê Đá Xay Kem & Barista Take Away [Menu 2026]', 'description' => 'Khóa học pha chế cà phê đá xay kem, smoothies và cà phê take away tại Passion Link: Thực hành 100% trên máy pha chuyên nghiệp, hỗ trợ lên menu mở quán.', 'h1' => 'Khóa Học Dạy Pha Chế Cà Phê Đá Xay Kem, Take Away & Smoothies Barista Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-mo-quan-tra-sua-tron-khoa-menu-ngon-72.html' => array('id' => 72, 'title' => 'Khóa Học Dạy Pha Chế Mở Quán Trà Sữa Chuẩn Vị Trọn Khóa [Menu 2026]', 'description' => 'Khóa học dạy pha chế mở quán trà sữa trọn khóa menu ngon chuẩn vị thực chiến tại Passion Link: 100% thực hành, hỗ trợ lên menu, tính cost giá vốn và đồng hành mở quán.', 'h1' => 'Khóa Học Dạy Pha Chế Mở Quán Trà Sữa Chuẩn Vị Trọn Khóa Menu Ngon'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-sinh-to-nuoc-ep-chuyen-nghiep-59.html' => array('id' => 59, 'title' => 'Khóa Học Dạy Pha Chế Sinh Tố & Nước Ép Chuyên Nghiệp [Menu 2026]', 'description' => 'Khóa học pha chế sinh tố và nước ép trái cây chuẩn vị mở quán tại Passion Link: Kỹ thuật giữ màu tươi nguyên bản, bảo toàn vitamin và cân bằng hương vị hoàn hảo.', 'h1' => 'Khóa Học Dạy Pha Chế Sinh Tố & Nước Ép Chuyên Nghiệp Ngon Chuẩn Vị'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-tra-sua-tran-chau-tra-thai-34.html' => array('id' => 34, 'title' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu, Trà Thái [Menu 2026]', 'description' => 'Khóa học dạy pha chế trà sữa trân châu, trà Thái chuẩn vị mở quán tại Passion Link: 100% thực hành, hướng dẫn ủ trà đậm vị và tính cost giá vốn.', 'h1' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu & Trà Thái Ngon Chuẩn Vị Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-tra-sua-tran-chau-tra-thai-ngon-34.html' => array('id' => 34, 'title' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu, Trà Thái [Menu 2026]', 'description' => 'Khóa học dạy pha chế trà sữa trân châu, trà Thái chuẩn vị mở quán tại Passion Link: 100% thực hành, hướng dẫn ủ trà đậm vị và tính cost giá vốn.', 'h1' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu & Trà Thái Ngon Chuẩn Vị Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/hoc-by-quyet-tra-sua-ngon-chuan-vi-dai-loan-tu-1980-tu-tin-mo-quan-nam-2019-219.html' => array('id' => 219, 'title' => 'Khóa Học Trà Sữa Chuẩn Vị Đài Loan Từ 1980 Mở Quán [Menu 2026]', 'description' => 'Khóa học pha chế trà sữa chuẩn vị Đài Loan truyền thống từ 1980 tại Passion Link: Bí quyết ủ trà đen, trà ô long đậm đà chuẩn gu khách hàng để tự tin mở quán.', 'h1' => 'Học Pha Chế Trà Sữa Ngon Chuẩn Vị Đài Loan Từ 1980 Tự Tin Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/hoc-pha-che-tra-sua-tran-chau-khac-biet-day-bi-quyet-pha-che-tu-rau-cu-trai-cay-hoa-la-organic-110.html' => array('id' => 110, 'title' => 'Khóa Học Trà Sữa Đậm Đà Từ Trái Cây & Hoa Lá Organic [Menu 2026]', 'description' => 'Khóa học dạy bí quyết pha chế trà sữa khác biệt từ rau củ, trái cây tươi và hoa lá organic tại Passion Link: Hương vị tự nhiên độc đáo, dẫn đầu xu hướng.', 'h1' => 'Học Pha Chế Trà Sữa Đậm Đà - Bí Quyết Pha Chế Từ Rau Củ Trái Cây Tươi'),
            '/cac-khoa-hoc-day-pha-che/khoa-ca-phe-barista-chuyen-nghiep-137.html' => array('id' => 137, 'title' => 'Khóa Học Cà Phê Pha Máy Barista Chuyên Nghiệp [Menu 2026]', 'description' => 'Khóa đào tạo Barista cà phê pha máy chuyên nghiệp tại Passion Link: Chiết xuất Espresso chuẩn tỉ lệ, kỹ thuật đánh sữa bọt mịn và tạo hình Latte Art nghệ thuật.', 'h1' => 'Khóa Học Cà Phê Pha Máy Barista Chuyên Nghiệp Mở Quán Hiện Đại'),
            '/cac-khoa-hoc-day-pha-che/khoa-dao-tao-chuyen-gia-ve-tra-va-mo-chuoi-nhuong-quyen-245.html' => array('id' => 245, 'title' => 'Khóa Đào Tạo Chuyên Gia Về Trà & Mở Chuỗi Nhượng Quyền [Menu 2026]', 'description' => 'Khóa đào tạo chuyên sâu về kỹ thuật sản xuất trà, phối vị và xây dựng chuỗi trà sữa nhượng quyền tại Passion Link: Dành riêng cho chủ thương hiệu và chuỗi F&B.', 'h1' => 'Khóa Đào Tạo Chuyên Gia Về Trà & Mở Chuỗi Nhượng Quyền Trà Sữa'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-banh-kem-tra-sua-tran-chau-duong-den-2019-220.html' => array('id' => 220, 'title' => 'Khóa Học Làm Bánh Kem Trà Sữa Trân Châu Đường Đen [Menu 2026]', 'description' => 'Khóa học làm bánh kem trà sữa trân châu đường đen sốt chảy thơm ngon tại Passion Link: Cốt bánh xốp mịn hòa quyện lớp kem trà sữa béo ngậy và trân châu dẻo mềm.', 'h1' => 'Khóa Học Làm Bánh Kem Trà Sữa Trân Châu Đường Đen Ngon Mê Ly Mở Quán'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-cac-mon-an-vat-cho-quan-tra-sua-va-ca-phe-241.html' => array('id' => 241, 'title' => 'Khóa Học Các Món Ăn Vặt Cho Quán Trà Sữa & Cà Phê [Menu 2026]', 'description' => 'Khóa học chế biến các món ăn vặt đắt khách cho quán trà sữa, cà phê tại Passion Link: Tối ưu chi phí quầy bar, chế biến nhanh và nhân đôi doanh thu cho quán.', 'h1' => 'Khóa Học Các Món Ăn Vặt Ngon Mở Quán Trà Sữa Cà Phê Hút Khách'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-che-dai-loan-chuan-hieu-ban-co-biet-meet-fresh-va-blackball-120.html' => array('id' => 120, 'title' => 'Khóa Học Nấu Chè Đài Loan Chuẩn Hiệu Meet Fresh & Blackball [2026]', 'description' => 'Khóa học nấu chè Đài Loan khoai dẻo, thạch thảo mộc chuẩn vị Meet Fresh & Blackball tại Passion Link: Công thức chuẩn vị thơm lành, nâng tầm menu tráng miệng.', 'h1' => 'Khóa Học Nấu Chè Đài Loan Chuẩn Vị Thương Hiệu Meet Fresh & Blackball'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-menu-thuong-hieu-tra-sua-223.html' => array('id' => 223, 'title' => 'Khóa Học Pha Chế Trà Sữa Thương Hiệu Chuyên Nghiệp [Menu 2026]', 'description' => 'Khóa đào tạo pha chế trà sữa thương hiệu cao cấp tại Passion Link: Thiết kế menu độc quyền, định vị thương hiệu, kiểm soát cost và vận hành chuỗi chuyên nghiệp.', 'h1' => 'Khóa Học Pha Chế Trà Sữa Thương Hiệu - Professional Milktea Course'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-tau-hu-thai-mon-ngon-bi-truyen-136.html' => array('id' => 136, 'title' => 'Khóa Học Làm Tàu Hủ Thái Chuẩn Vị Mềm Mịn [Menu 2026]', 'description' => 'Khóa học làm tàu hủ Thái mềm mịn chuẩn công thức bí truyền tại Passion Link: Kỹ thuật đổ bánh núng nính, kết hợp các loại nước sốt trái cây và topping thơm ngon.', 'h1' => 'Khóa Học Làm Tàu Hủ Thái Chuẩn Vị - Bánh Tàu Hủ Mềm Mịn Chuẩn Thái'),
            '/cac-khoa-hoc-day-pha-che/khoa-hoc-tra-trai-cay-nhiet-doi-177.html' => array('id' => 177, 'title' => 'Khóa Học Pha Chế Trà Trái Cây Nhiệt Đới Đậm Vị [Menu 2026]', 'description' => 'Khóa học pha chế trà trái cây nhiệt đới với 10 món hot trend nhất tại Passion Link: Bí quyết phối cốt trà thanh mát kết hợp hoa quả tươi nguyên vị hút khách.', 'h1' => 'Khóa Học Pha Chế Trà Trái Cây Nhiệt Đới - Menu 10 Món Hot Trend Nhất'),
            '/cac-khoa-hoc-day-pha-che/khoa-pha-che-tong-hop-7-menu-thuc-uong-noi-tieng-229.html' => array('id' => 229, 'title' => 'Khóa Học Pha Chế Tổng Hợp 7 Menu Đồ Uống Mở Quán [Menu 2026]', 'description' => 'Khóa học pha chế tổng hợp 7 menu thức uống nổi tiếng tại Passion Link: Trọn gói trà sữa, cà phê, trà trái cây, đá xay, sinh tố nước ép mở quán tự tin 100%.', 'h1' => 'Khóa Học Pha Chế Tổng Hợp Trà Sữa, Trà Trái Cây, Cà Phê, Sinh Tố Nước Ép'),
            '/cac-khoa-hoc-day-pha-che/tra-chanh-la-gi-khoa-hoc-menu-tra-chanh-hot-nhat-259.html' => array('id' => 259, 'title' => 'Khóa Học Pha Chế Trà Chanh Hiện Đại Hot Trend [Menu 2026]', 'description' => 'Khóa học pha chế trà chanh hiện đại kết hợp trái cây tươi tại Passion Link: Vốn ít, lợi nhuận cao, hoàn vốn nhanh, công thức đậm đà độc quyền mở quán đắt khách.', 'h1' => 'Khóa Học Pha Chế Trà Chanh Hiện Đại Hot Nhất - Trà Chanh Trái Cây Tươi'),
            '/cac-khoa-hoc-day-pha-che/trang/1' => array('id' => 0, 'title' => 'Các Khóa Học Pha Chế Mở Quán Chuyên Nghiệp - Trang 1 [2026]', 'description' => 'Danh sách các khóa học pha chế trà sữa, cà phê barista, sinh tố nước ép mở quán tại Passion Link - Trang 1. Xem lịch khai giảng và học phí ưu đãi ngay!', 'h1' => 'Tổng Hợp Các Khóa Học Dạy Pha Chế Chuyên Nghiệp Mở Quán (Trang 1)'),
            '/cac-khoa-hoc-day-pha-che/trang/2' => array('id' => 0, 'title' => 'Các Khóa Học Pha Chế Mở Quán Chuyên Nghiệp - Trang 2 [2026]', 'description' => 'Danh sách các khóa học pha chế trà sữa, cà phê barista, sinh tố nước ép mở quán tại Passion Link - Trang 2. Xem lịch khai giảng và học phí ưu đãi ngay!', 'h1' => 'Tổng Hợp Các Khóa Học Dạy Pha Chế Chuyên Nghiệp Mở Quán (Trang 2)'),
            '/quan-hoc-vien-thanh-cong/avartar-114.html' => array('id' => 114, 'title' => 'Học Viên Thành Công: Câu Chuyện Mở Quán Trà Sữa Avatar', 'description' => 'Khám phá mô hình kinh doanh quán trà sữa Avatar của học viên Passion Link: Tối ưu chi phí, menu hút khách và vận hành hiệu quả.', 'h1' => 'Học Viên Passion Link Mở Quán Trà Sữa Avatar Khởi Nghiệp Thành Công'),
            '/quan-hoc-vien-thanh-cong/chuoi-tra-sua-ilacha-142.html' => array('id' => 142, 'title' => 'Học Viên Thành Công: Câu Chuyện Mở Quán Chuỗi Trà Sữa Ilacha', 'description' => 'Khám phá hành trình khởi nghiệp thành công của học viên Passion Link với chuỗi thương hiệu trà sữa Ilacha phát triển vượt bậc.', 'h1' => 'Học Viên Passion Link Mở Chuỗi Trà Sữa Ilacha Khởi Nghiệp Thành Công'),
            '/quan-hoc-vien-thanh-cong/gutea-116.html' => array('id' => 116, 'title' => 'Học Viên Thành Công: Câu Chuyện Mở Quán Trà Sữa Gutea', 'description' => 'Hành trình từ khóa học pha chế tại Passion Link đến khi làm chủ thương hiệu trà sữa Gutea được giới trẻ yêu thích.', 'h1' => 'Học Viên Passion Link Mở Quán Trà Sữa Gutea Thành Công'),
            '/quan-hoc-vien-thanh-cong/m-s-jolly-113.html' => array('id' => 113, 'title' => 'Học Viên Thành Công: Câu Chuyện Mở Quán Trà Sữa M\'s Jolly', 'description' => 'Chia sẻ kinh nghiệm mở quán trà sữa M\'s Jolly thành công sau khi hoàn thành khóa đào tạo pha chế chuyên sâu tại Passion Link.', 'h1' => 'Học Viên Passion Link Mở Quán Trà Sữa M\'s Jolly Thành Công'),
            '/quan-hoc-vien-thanh-cong/royaltea-vietnam-117.html' => array('id' => 117, 'title' => 'Học Viên Thành Công: Câu Chuyện Mở Quán Trà Sữa Royaltea Việt Nam', 'description' => 'Câu chuyện khởi nghiệp thực tế từ học viên Passion Link với thương hiệu nhượng quyền trà sữa Royaltea Việt Nam đông khách.', 'h1' => 'Học Viên Passion Link Mở Quán Trà Sữa Royaltea Việt Nam Thành Công'),
            '/doi-ngu-giang-vien/co-thoai-vy-139.html' => array('id' => 139, 'title' => 'Cô Thoại Vy - Chuyên Gia Đào Tạo Pha Chế Hàng Đầu | Passion Link', 'description' => 'Giảng viên Thoại Vy - Chuyên gia pha chế và sáng tạo đồ uống hàng đầu tại Học viện Passion Link với bề dày kinh nghiệm đào tạo thực chiến.', 'h1' => 'Cô Thoại Vy - Giảng Viên & Chuyên Gia Sáng Tạo Đồ Uống Passion Link'),
            '/doi-ngu-giang-vien/thay-cuong-barista-140.html' => array('id' => 140, 'title' => 'Thầy Cường Barista - Chuyên Gia Đào Tạo Cà Phê Hàng Đầu | Passion Link', 'description' => 'Chuyên gia Cường Barista - Huấn luyện viên Barista chuyên nghiệp tại Passion Link, chuyên sâu về pha chế cà phê máy, latte art và setup quầy bar.', 'h1' => 'Thầy Cường Barista - Huấn Luyện Viên Barista Chuyên Nghiệp Passion Link'),
            '/doi-ngu-giang-vien/thay-duc-anh-118.html' => array('id' => 118, 'title' => 'Thầy Đức Anh - Chuyên Gia Đào Tạo Pha Chế Hàng Đầu | Passion Link', 'description' => 'Giảng viên Đức Anh - Chuyên gia đào tạo kỹ thuật pha chế thực chiến tại Passion Link, đồng hành cùng học viên từ công thức đến vận hành quán.', 'h1' => 'Thầy Đức Anh - Giảng Viên Đào Tạo Pha Chế Thực Chiến Passion Link'),
            '/doi-ngu-giang-vien/thay-le-huu-tri-105.html' => array('id' => 105, 'title' => 'Thầy Lê Hữu Trí - Chuyên Gia Đào Tạo Pha Chế Hàng Đầu | Passion Link', 'description' => 'Chuyên gia Lê Hữu Trí với hơn 15+ năm kinh nghiệm đào tạo pha chế, cố vấn chiến lược và đồng hành mở quán thành công cho hàng ngàn chủ quán trên toàn quốc.', 'h1' => 'Thầy Lê Hữu Trí - Chuyên Gia Đào Tạo & Cố Vấn Khởi Nghiệp F&B'),
            '/mo-quan/10-y-tuong-kinh-doanh-quan-ca-phe-va-tra-sua-cuc-hot-233.html' => array('id' => 233, 'title' => '10 Ý Tưởng Kinh Doanh Quán Cà Phê và Trà Sữa Cực Hot [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về 10 ý tưởng kinh doanh quán cà phê và trà sữa cực hot từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân ...', 'h1' => '10 Ý Tưởng Kinh Doanh Quán Cà Phê và Trà Sữa Cực Hot'),
            '/mo-quan/5-cong-thu-c-smoothie-tra-i-cay-giu-p-gia-m-can-to-t-cho-su-c-kho-e-131.html' => array('id' => 131, 'title' => '5 Công Thức Smoothie Trái Cây Giúp Giảm Cân, Tốt cho Sức Khỏe', 'description' => 'Chia sẻ kinh nghiệm thực tế về 5 công thức smoothie trái cây giúp giảm cân, tốt cho sức khỏe từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điể...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: 5 Công Thức Smoothie Trái Cây Giúp Giảm Cân, Tốt cho Sức Khỏe'),
            '/mo-quan/5-kinh-nghiem-cach-tim-thue-mat-bang-mo-quan-tra-sua-231.html' => array('id' => 231, 'title' => '5 Kinh Nghiệm Cách Tìm Thuê Mặt Bằng Mở Quán Trà Sữa [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về 5 kinh nghiệm cách tìm thuê mặt bằng mở quán trà sữa từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân ...', 'h1' => '5 Kinh Nghiệm Cách Tìm Thuê Mặt Bằng Mở Quán Trà Sữa'),
            '/mo-quan/5-nguyen-nhan-that-bai-cua-tra-sua-ten-ren-243.html' => array('id' => 243, 'title' => '5 Nguyên Nhân Thất Bại của Trà Sữa Ten Ren [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về 5 nguyên nhân thất bại của trà sữa ten ren từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và se...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: 5 Nguyên Nhân Thất Bại của Trà Sữa Ten Ren'),
            '/mo-quan/7-cach-hay-de-chon-mua-may-ca-phe-barista-y-226.html' => array('id' => 226, 'title' => '7 Cách Hay để Chọn Mua Máy Cà Phê BARISTA Ý [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về 7 cách hay để chọn mua máy cà phê barista ý từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và s...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: 7 Cách Hay để Chọn Mua Máy Cà Phê BARISTA Ý'),
            '/mo-quan/bi-kip-duy-tri-hoat-dong-kinh-doanh-quan-cafe-tra-sua-179.html' => array('id' => 179, 'title' => 'Bí Kíp Duy Trì Hoạt Động Kinh Doanh Quán Café/ Trà Sữa [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về bí kíp duy trì hoạt động kinh doanh quán café/ trà sữa từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhâ...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Bí Kíp Duy Trì Hoạt Động Kinh Doanh Quán Café/ Trà Sữa'),
            '/mo-quan/bi-quyet-chon-mua-bo-dung-cu-pha-che-ca-phe-barista-chuyen-nghiep-232.html' => array('id' => 232, 'title' => 'Bí Quyết Chọn Mua Bộ Dụng Cụ Pha Chế Cà Phê BARISTA Chuyên Nghiệp', 'description' => 'Chia sẻ kinh nghiệm thực tế về bí quyết chọn mua bộ dụng cụ pha chế cà phê barista chuyên nghiệp từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, ...', 'h1' => 'Bí Quyết Chọn Mua Bộ Dụng Cụ Pha Chế Cà Phê BARISTA Chuyên Nghiệp'),
            '/mo-quan/cach-dat-ten-tieng-anh-cho-menu-cac-mon-tra-sua-noi-tieng-234.html' => array('id' => 234, 'title' => 'Cách Đặt Tên Tiếng Anh cho Menu Các Món Trà Sữa Nổi Tiếng [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về cách đặt tên tiếng anh cho menu các món trà sữa nổi tiếng từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý ...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Cách Đặt Tên Tiếng Anh cho Menu Các Món Trà Sữa Nổi Tiếng'),
            '/mo-quan/cach-kinh-doanh-mo-hinh-tra-sua-ca-phe-xe-tai-nho-227.html' => array('id' => 227, 'title' => 'Cách Kinh Doanh Mô Hình Trà Sữa Cà Phê Xe Tải Nhỏ [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về cách kinh doanh mô hình trà sữa cà phê xe tải nhỏ từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viê...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Cách Kinh Doanh Mô Hình Trà Sữa Cà Phê Xe Tải Nhỏ'),
            '/mo-quan/cach-tao-tai-khoan-facebook-cho-quan-tra-sua-va-ca-phe-238.html' => array('id' => 238, 'title' => 'Cách Tạo Tài Khoản Facebook cho Quán Trà Sữa và Cà Phê [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về cách tạo tài khoản facebook cho quán trà sữa và cà phê từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhâ...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Cách Tạo Tài Khoản Facebook cho Quán Trà Sữa và Cà Phê'),
            '/mo-quan/cach-tao-trang-fanpage-cho-quan-tra-sua-va-ca-phe-239.html' => array('id' => 239, 'title' => 'Cách Tạo Trang Fanpage cho Quán Trà Sữa và Cà Phê [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về cách tạo trang fanpage cho quán trà sữa và cà phê từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viê...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Cách Tạo Trang Fanpage cho Quán Trà Sữa và Cà Phê'),
            '/mo-quan/cach-tao-zalo-page-cho-quan-tra-sua-va-ca-phe-chi-tiet-nhat-2019-236.html' => array('id' => 236, 'title' => 'Cách Tạo Zalo Page cho Quán Trà Sữa và Cà Phê Chi Tiết Nhất 2019', 'description' => 'Chia sẻ kinh nghiệm thực tế về cách tạo zalo page cho quán trà sữa và cà phê chi tiết nhất 2019 từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, q...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Cách Tạo Zalo Page cho Quán Trà Sữa và Cà Phê Chi Tiết Nhất 2019'),
            '/mo-quan/che-trang-mieng-meet-fresh-dai-loan-ban-co-biet-121.html' => array('id' => 121, 'title' => 'Chè Tráng Miệng Meet Fresh Đài Loan - Bạn Có Biết [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về chè tráng miệng meet fresh đài loan - bạn có biết từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viê...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Chè Tráng Miệng Meet Fresh Đài Loan - Bạn Có Biết'),
            '/mo-quan/dau-la-nguyen-nhan-khien-cho-kinh-doanh-tra-sua-that-bai-178.html' => array('id' => 178, 'title' => 'Mở Quán Trà Sữa Hút Khách Nườm Nượp – Đừng Bỏ Qua 6 Yếu Tố Sau', 'description' => 'Chia sẻ kinh nghiệm thực tế về mở quán trà sữa hút khách nườm nượp – đừng bỏ qua 6 yếu tố sau từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quả...', 'h1' => 'Mở Quán Trà Sữa Hút Khách Nườm Nượp – Đừng Bỏ Qua 6 Yếu Tố Sau'),
            '/mo-quan/di-nh-gia-cho-menu-cu-a-ba-n-130.html' => array('id' => 130, 'title' => 'Định Giá cho Menu Của Bạn [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về định giá cho menu của bạn từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và setup quầy bar ...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Định Giá cho Menu Của Bạn'),
            '/mo-quan/huong-dan-cach-tao-tai-khoan-zalo-quan-tra-sua-ca-phe-235.html' => array('id' => 235, 'title' => 'Hướng Dẫn Cách Tạo Tài Khoản Zalo Quán Trà Sữa Cà Phê [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về hướng dẫn cách tạo tài khoản zalo quán trà sữa cà phê từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân...', 'h1' => 'Hướng Dẫn Cách Tạo Tài Khoản Zalo Quán Trà Sữa Cà Phê'),
            '/mo-quan/huong-dan-tao-google-place-cho-quan-tra-sua-va-ca-phe-237.html' => array('id' => 237, 'title' => 'Hướng Dẫn Tạo Google Place cho Quán Trà Sữa và Cà Phê [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về hướng dẫn tạo google place cho quán trà sữa và cà phê từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân...', 'h1' => 'Hướng Dẫn Tạo Google Place cho Quán Trà Sữa và Cà Phê'),
            '/mo-quan/khoa-hoc-lam-kem-tuoi-ngon-kinh-doanh-cua-hang-kem-250.html' => array('id' => 250, 'title' => 'Khóa Học Làm Kem Tươi Ngon Mở Quán Kinh Doanh [Menu 2026]', 'description' => 'Khóa học làm kem tươi mở quán kinh doanh chuyên nghiệp tại Passion Link: Kỹ thuật vận hành máy làm kem, công thức kem tươi mềm mịn thơm béo chuẩn vị.', 'h1' => 'Khóa Học Làm Kem Tươi Ngon Kinh Doanh Mở Cửa Hàng Kem Chuyên Nghiệp'),
            '/mo-quan/khoa-hoc-lam-kem-vien-phap-kinh-doanh-mo-quan-252.html' => array('id' => 252, 'title' => 'Khóa Học Làm Kem Viên Pháp Kinh Doanh Mở Quán [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về khóa học làm kem viên pháp kinh doanh mở quán từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và...', 'h1' => 'Khóa Học Làm Kem Viên Pháp Kinh Doanh Mở Quán'),
            '/mo-quan/khoa-hoc-menu-an-vat-mo-quan-251.html' => array('id' => 251, 'title' => 'Khóa Học Menu Ăn Vặt Mở Quán [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về khóa học menu ăn vặt mở quán từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và setup quầy bar c...', 'h1' => 'Khóa Học Menu Ăn Vặt Mở Quán'),
            '/mo-quan/khoa-hoc-pha-che-ca-phe-phin-mo-quan-247.html' => array('id' => 247, 'title' => 'Khóa Học Pha Chế Cà Phê Phin - Cà Phê Truyền Thống [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về khóa học pha chế cà phê phin - cà phê truyền thống từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân vi...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Khóa Học Pha Chế Cà Phê Phin - Cà Phê Truyền Thống'),
            '/mo-quan/khoa-hoc-pha-che-tra-sua-hoa-qua-chuan-vi-tu-nam-1980-119.html' => array('id' => 119, 'title' => 'Khóa Học Pha Chế Trà Sữa Hoa Quả Chuẩn Vị từ Năm 1980 [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về khóa học pha chế trà sữa hoa quả chuẩn vị từ năm 1980 từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Khóa Học Pha Chế Trà Sữa Hoa Quả Chuẩn Vị từ Năm 1980'),
            '/mo-quan/khoa-hoc-pha-che-tra-sua-khac-biet-mo-quan-248.html' => array('id' => 248, 'title' => 'Khóa Học Pha Chế Trà Sữa Khác Biệt Mở Quán [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về khóa học pha chế trà sữa khác biệt mở quán từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và se...', 'h1' => 'Khóa Học Pha Chế Trà Sữa Khác Biệt Mở Quán'),
            '/mo-quan/khoa-hoc-tron-bo-menu-tong-hop-hot-nhat-2019-253.html' => array('id' => 253, 'title' => 'Khóa Học Trọn Bộ Menu Đồ Uống Mở Quán Tổng Hợp [Menu 2026]', 'description' => 'Khóa học trọn bộ menu tổng hợp đồ uống mở quán hot nhất tại Passion Link: Đầy đủ trà sữa, trà trái cây, cà phê, đá xay và kỹ năng quản lý vận hành quán.', 'h1' => 'Khóa Học Pha Chế Trọn Bộ Menu Đồ Uống Tổng Hợp Hot Nhất Mở Quán'),
            '/mo-quan/mo-quan-cafe-tra-sua-can-chuan-bi-nhung-gi-181.html' => array('id' => 181, 'title' => 'Mở Quán Cafe - Trà Sữa Cần Chuẩn Bị Những Gì [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về mở quán cafe - trà sữa cần chuẩn bị những gì từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và ...', 'h1' => 'Mở Quán Cafe - Trà Sữa Cần Chuẩn Bị Những Gì'),
            '/mo-quan/mo-quan-tra-sua-can-chuan-bi-bao-nhieu-von-135.html' => array('id' => 135, 'title' => 'Mở Quán Trà Sữa Cần Chuẩn Bị Bao Nhiêu Vốn [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về mở quán trà sữa cần chuẩn bị bao nhiêu vốn từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và se...', 'h1' => 'Mở Quán Trà Sữa Cần Chuẩn Bị Bao Nhiêu Vốn'),
            '/mo-quan/mo-quan-tra-sua-can-mua-nhung-dung-cu-va-may-moc-gi-quan-trong-115.html' => array('id' => 115, 'title' => 'Mở Quán Trà Sữa Cần Mua Những Dụng Cụ và Máy Móc Gì Quan Trọng', 'description' => 'Chia sẻ kinh nghiệm thực tế về mở quán trà sữa cần mua những dụng cụ và máy móc gì quan trọng từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quả...', 'h1' => 'Mở Quán Trà Sữa Cần Mua Những Dụng Cụ và Máy Móc Gì Quan Trọng'),
            '/mo-quan/nhung-phong-cach-quan-tra-sua-duoc-yeu-thich-nhat-180.html' => array('id' => 180, 'title' => 'Những Phong Cách Quán Trà Sữa Được Yêu Thích Nhất [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về những phong cách quán trà sữa được yêu thích nhất từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viê...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Những Phong Cách Quán Trà Sữa Được Yêu Thích Nhất'),
            '/mo-quan/thoi-diem-tot-nhat-de-mo-quan-cafe-tra-sua-217.html' => array('id' => 217, 'title' => 'Thời Điểm Tốt Nhất để Mở Quán Café/ Trà Sữa [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về thời điểm tốt nhất để mở quán café/ trà sữa từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên và s...', 'h1' => 'Thời Điểm Tốt Nhất để Mở Quán Café/ Trà Sữa'),
            '/mo-quan/thu-thuat-kinh-doanh-giup-quan-tra-sua-cua-ban-luon-luon-dong-khach-182.html' => array('id' => 182, 'title' => 'Thủ Thuật Kinh Doanh Giúp Quán Trà Sữa của Bạn Luôn Luôn Đông Khách', 'description' => 'Chia sẻ kinh nghiệm thực tế về thủ thuật kinh doanh giúp quán trà sữa của bạn luôn luôn đông khách từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Thủ Thuật Kinh Doanh Giúp Quán Trà Sữa của Bạn Luôn Luôn Đông Khách'),
            '/mo-quan/thu-tuc-dang-ky-kinh-doanh-mo-quan-cafe-tra-sua-218.html' => array('id' => 218, 'title' => 'Thủ Tục Đăng Ký Kinh Doanh Mở Quán Café Trà Sữa [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về thủ tục đăng ký kinh doanh mở quán café trà sữa từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên ...', 'h1' => 'Thủ Tục Đăng Ký Kinh Doanh Mở Quán Café Trà Sữa'),
            '/mo-quan/tra-chanh-tro-lai-mo-ra-co-hoi-kinh-doanh-sieu-loi-260.html' => array('id' => 260, 'title' => 'Trà Chanh Trở Lại Mở Ra Cơ Hội Kinh Doanh Siêu Lời [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về trà chanh trở lại mở ra cơ hội kinh doanh siêu lời từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân vi...', 'h1' => 'Hướng Dẫn Kinh Nghiệm Mở Quán: Trà Chanh Trở Lại Mở Ra Cơ Hội Kinh Doanh Siêu Lời'),
            '/mo-quan/trang/1' => array('id' => 0, 'title' => 'Cẩm Nang & Kinh Nghiệm Mở Quán Trà Sữa, Cà Phê - Trang 1 [2026]', 'description' => 'Tổng hợp kinh nghiệm mở quán trà sữa, cà phê từ A-Z: Chi phí, chọn mặt bằng, mua máy móc quầy bar và tối ưu vận hành - Trang 1.', 'h1' => 'Cẩm Nang Hướng Dẫn & Kinh Nghiệm Mở Quán Trà Sữa, Cà Phê (Trang 1)'),
            '/mo-quan/trang/2' => array('id' => 0, 'title' => 'Cẩm Nang & Kinh Nghiệm Mở Quán Trà Sữa, Cà Phê - Trang 2 [2026]', 'description' => 'Tổng hợp kinh nghiệm mở quán trà sữa, cà phê từ A-Z: Chi phí, chọn mặt bằng, mua máy móc quầy bar và tối ưu vận hành - Trang 2.', 'h1' => 'Cẩm Nang Hướng Dẫn & Kinh Nghiệm Mở Quán Trà Sữa, Cà Phê (Trang 2)'),
            '/mo-quan/y-tuong-quan-ca-phe-ninja-nhat-ban-doc-dao-vtv24-242.html' => array('id' => 242, 'title' => 'Ý Tưởng Quán Cà Phê Ninja Nhật Bản Độc Đáo VTV24 [2026]', 'description' => 'Chia sẻ kinh nghiệm thực tế về ý tưởng quán cà phê ninja nhật bản độc đáo vtv24 từ chuyên gia Passion Link: Dự toán chi phí, chọn địa điểm, quản lý nhân viên...', 'h1' => 'Ý Tưởng Quán Cà Phê Ninja Nhật Bản Độc Đáo VTV24'),
            '/day-pha-che-tra-sua-ngon/13-meo-de-mo-mot-quan-ca-phe-thanh-cong-157.html' => array('id' => 157, 'title' => 'Cách Làm 13 Mẹo để Mở Một Quán Cà Phê Thành Công Chuẩn Vị [Công T...', 'description' => 'Hướng dẫn cách làm 13 mẹo để mở một quán cà phê thành công chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật l...', 'h1' => 'Công Thức & Cách Pha 13 Mẹo để Mở Một Quán Cà Phê Thành Công Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/15-cau-kinh-dien-thay-co-nao-cung-tung-noi-hoc-sinh-nghe-den-thuoc-lau-lau-161.html' => array('id' => 161, 'title' => 'Cách Làm 15 Câu Kinh Điển Thầy Cô Nào Cũng Từng Nói, Học Sinh Ngh...', 'description' => 'Hướng dẫn cách làm 15 câu kinh điển thầy cô nào cũng từng nói, học sinh nghe đến thuộc làu làu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm ...', 'h1' => 'Công Thức & Cách Pha 15 Câu Kinh Điển Thầy Cô Nào Cũng Từng Nói, Học Sinh Nghe Đến Thuộc Làu Làu Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/15-loai-mut-khong-the-thieu-trong-dip-tet-196.html' => array('id' => 196, 'title' => 'Cách Làm 15 Loại Mứt Không Thể Thiếu trong Dịp Tết Chuẩn Vị [Công...', 'description' => 'Hướng dẫn cách làm 15 loại mứt không thể thiếu trong dịp tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật...', 'h1' => 'Công Thức & Cách Pha 15 Loại Mứt Không Thể Thiếu trong Dịp Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/3-cach-nau-xoi-cung-ngay-tet-cho-nam-moi-them-may-man-207.html' => array('id' => 207, 'title' => 'Cách Làm 3 Cách Nấu Xôi Cúng Ngày Tết cho Năm Mới Thêm May Mắn Ch...', 'description' => 'Hướng dẫn cách làm 3 cách nấu xôi cúng ngày tết cho năm mới thêm may mắn chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Công Thức & Cách Pha 3 Cách Nấu Xôi Cúng Ngày Tết cho Năm Mới Thêm May Mắn Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/3-cong-thuc-quan-trong-trong-pha-che-tra-sua-144.html' => array('id' => 144, 'title' => 'Cách Làm 3 Công Thức Quan Trọng trong Pha Chế Trà Sữa Chuẩn Vị [C...', 'description' => 'Hướng dẫn cách làm 3 công thức quan trọng trong pha chế trà sữa chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên ...', 'h1' => '3 Công Thức Quan Trọng trong Pha Chế Trà Sữa'),
            '/day-pha-che-tra-sua-ngon/5-buoc-quan-trong-de-ban-chon-mua-may-pha-ca-phe-156.html' => array('id' => 156, 'title' => 'Cách Làm 5 Bước Quan Trọng để Bạn Chọn Mua Máy Pha Cà Phê Chuẩn V...', 'description' => 'Hướng dẫn cách làm 5 bước quan trọng để bạn chọn mua máy pha cà phê chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Công Thức & Cách Pha 5 Bước Quan Trọng để Bạn Chọn Mua Máy Pha Cà Phê Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/5-cach-de-danh-gia-chat-luong-matcha-164.html' => array('id' => 164, 'title' => 'Cách Làm 5 Cách để Đánh Giá Chất Lượng Matcha Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm 5 cách để đánh giá chất lượng matcha chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Công Thức & Cách Pha 5 Cách để Đánh Giá Chất Lượng Matcha Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/5-loai-do-uong-than-thanh-giup-bung-phang-li-sau-tet-194.html' => array('id' => 194, 'title' => 'Cách Làm 5 Loại “đồ Uống Thần Thánh” Giúp Bụng Phẳng Lì Sau Tết C...', 'description' => 'Hướng dẫn cách làm 5 loại “đồ uống thần thánh” giúp bụng phẳng lì sau tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi p...', 'h1' => 'Công Thức & Cách Pha 5 Loại “đồ Uống Thần Thánh” Giúp Bụng Phẳng Lì Sau Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/5-tuyet-chieu-tang-gia-do-uong-ma-khach-hang-ma-khach-hang-van-mim-cuoi-183.html' => array('id' => 183, 'title' => 'Cách Làm 5 Tuyệt Chiêu Tăng Giá Đồ Uống Mà Khách Hàng Vẫn Mỉm Cườ...', 'description' => 'Hướng dẫn cách làm 5 tuyệt chiêu tăng giá đồ uống mà khách hàng vẫn mỉm cười chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ch...', 'h1' => 'Công Thức & Cách Pha 5 Tuyệt Chiêu Tăng Giá Đồ Uống Mà Khách Hàng Vẫn Mỉm Cười Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/5-yeu-to-anh-huong-den-chat-luong-cafe-espresso-143.html' => array('id' => 143, 'title' => 'Cách Làm 5 Yếu Tố Ảnh Hưởng Đến Chất Lượng Cafe ESPRESSO Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm 5 yếu tố ảnh hưởng đến chất lượng cafe espresso chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Công Thức & Cách Pha 5 Yếu Tố Ảnh Hưởng Đến Chất Lượng Cafe ESPRESSO Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/5-yeu-to-thiet-ke-quan-doc-la-160.html' => array('id' => 160, 'title' => 'Cách Làm 5 Yếu Tố Thiết Kế Quán Độc Lạ Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm 5 yếu tố thiết kế quán độc lạ chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem c...', 'h1' => 'Công Thức & Cách Pha 5 Yếu Tố Thiết Kế Quán Độc Lạ Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/6-buoc-dat-ten-cho-quan-ca-phe-159.html' => array('id' => 159, 'title' => 'Cách Làm 6 Bước Đặt Tên cho Quán Cà Phê Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm 6 bước đặt tên cho quán cà phê chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem ...', 'h1' => 'Công Thức & Cách Pha 6 Bước Đặt Tên cho Quán Cà Phê Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/6-cach-lam-salad-khai-vi-dau-xuan-206.html' => array('id' => 206, 'title' => 'Cách Làm 6 Cách Làm Salad Khai Vị Đầu Xuân Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm 6 cách làm salad khai vị đầu xuân chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. X...', 'h1' => '6 Cách Làm Salad Khai Vị Đầu Xuân'),
            '/day-pha-che-tra-sua-ngon/7-loai-hat-tot-cho-suc-khoe-nham-nhi-ngay-tet-208.html' => array('id' => 208, 'title' => 'Cách Làm 7 Loại Hạt Tốt cho Sức Khỏe Nhâm Nhi Ngày Tết Chuẩn Vị [...', 'description' => 'Hướng dẫn cách làm 7 loại hạt tốt cho sức khỏe nhâm nhi ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên...', 'h1' => 'Công Thức & Cách Pha 7 Loại Hạt Tốt cho Sức Khỏe Nhâm Nhi Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/7-loi-khuyen-giup-co-the-ban-hap-thu-tot-vitamin-170.html' => array('id' => 170, 'title' => 'Cách Làm 7 Lời Khuyên Giúp Cơ Thể Bạn Hấp Thụ Tốt Vitamin Chuẩn V...', 'description' => 'Hướng dẫn cách làm 7 lời khuyên giúp cơ thể bạn hấp thụ tốt vitamin chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Công Thức & Cách Pha 7 Lời Khuyên Giúp Cơ Thể Bạn Hấp Thụ Tốt Vitamin Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/7-mon-an-vat-ngay-tet-an-nhieu-den-may-cung-khong-so-tang-can-192.html' => array('id' => 192, 'title' => 'Cách Làm 7 Món Ăn Vặt Ngày Tết Ăn Nhiều Đến Mấy Cũng Không Sợ Tăn...', 'description' => 'Hướng dẫn cách làm 7 món ăn vặt ngày tết ăn nhiều đến mấy cũng không sợ tăng cân chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ư...', 'h1' => 'Công Thức & Cách Pha 7 Món Ăn Vặt Ngày Tết Ăn Nhiều Đến Mấy Cũng Không Sợ Tăng Cân Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/bat-mi-bi-mat-lam-kem-khoai-lang-tim-153.html' => array('id' => 153, 'title' => 'Cách Làm Bật Mí Bí Mật Làm Kem Khoai Lang Tím Dừa Chuẩn Vị [Công ...', 'description' => 'Hướng dẫn cách làm bật mí bí mật làm kem khoai lang tím dừa chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật ...', 'h1' => 'Công Thức & Cách Pha Bật Mí Bí Mật Làm Kem Khoai Lang Tím Dừa Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/bat-mi-bi-mat-lam-kem-khoai-lang-tim-dua-153.html' => array('id' => 153, 'title' => 'Cách Làm Bật Mí Bí Mật Làm Kem Khoai Lang Tím Dừa Chuẩn Vị [Công ...', 'description' => 'Hướng dẫn cách làm bật mí bí mật làm kem khoai lang tím dừa chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật ...', 'h1' => 'Công Thức & Cách Pha Bật Mí Bí Mật Làm Kem Khoai Lang Tím Dừa Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/bat-mi-cach-lam-mut-quat-ngon-khong-bi-dang-de-khong-ngo-205.html' => array('id' => 205, 'title' => 'Cách Làm Bật Mí Cách Làm Mứt Quất Ngon Không Bị Đắng Dễ Không Ngờ...', 'description' => 'Hướng dẫn cách làm bật mí cách làm mứt quất ngon không bị đắng dễ không ngờ chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi...', 'h1' => 'Bật Mí Cách Làm Mứt Quất Ngon Không Bị Đắng Dễ Không Ngờ'),
            '/day-pha-che-tra-sua-ngon/bi-quyet-luoc-banh-chung-xanh-ngon-dep-mat-cho-ngay-tet-them-ven-tron-185.html' => array('id' => 185, 'title' => 'Cách Làm Bí Quyết Luộc Bánh Chưng Xanh Ngon Đẹp Mắt- cho Ngày Tết...', 'description' => 'Hướng dẫn cách làm bí quyết luộc bánh chưng xanh ngon đẹp mắt- cho ngày tết thêm vẹn tròn chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương...', 'h1' => 'Bí Quyết Luộc Bánh Chưng Xanh Ngon Đẹp Mắt- cho Ngày Tết Thêm Vẹn Tròn'),
            '/day-pha-che-tra-sua-ngon/by-quyet-pha-tra-dao-ngon-tuyet-dinh-58.html' => array('id' => 58, 'title' => 'Cách Làm Bí Quyết Pha Trà Đào Ngon Tuyệt Đỉnh Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm bí quyết pha trà đào ngon tuyệt đỉnh chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Bí Quyết Pha Trà Đào Ngon Tuyệt Đỉnh'),
            '/day-pha-che-tra-sua-ngon/cach-chon-buoi-tet-dep-ngon-la-mat-209.html' => array('id' => 209, 'title' => 'Cách Làm Cách Chọn Bưởi Tết Đẹp – Ngon – Lạ Mắt Chuẩn Vị [Công Th...', 'description' => 'Hướng dẫn cách làm cách chọn bưởi tết đẹp – ngon – lạ mắt chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật li...', 'h1' => 'Công Thức & Cách Pha Cách Chọn Bưởi Tết Đẹp – Ngon – Lạ Mắt Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/cach-lam-banana-kiwi-smoothie-thom-ngon-bo-duong-176.html' => array('id' => 176, 'title' => 'Cách Làm Cách Làm Banana Kiwi Smoothie - Thơm Ngon, Bổ Dưỡng Chuẩ...', 'description' => 'Hướng dẫn cách làm cách làm banana kiwi smoothie - thơm ngon, bổ dưỡng chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ...', 'h1' => 'Cách Làm Banana Kiwi Smoothie - Thơm Ngon, Bổ Dưỡng'),
            '/day-pha-che-tra-sua-ngon/cach-lam-ca-chua-bi-deo-ngon-nham-nhi-ngay-tet-215.html' => array('id' => 215, 'title' => 'Cách Làm Cách Làm Cà Chua Bi Dẻo – Ngon Nhâm Nhi Ngày Tết Chuẩn V...', 'description' => 'Hướng dẫn cách làm cách làm cà chua bi dẻo – ngon nhâm nhi ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Cách Làm Cà Chua Bi Dẻo – Ngon Nhâm Nhi Ngày Tết'),
            '/day-pha-che-tra-sua-ngon/cach-lam-kem-sinh-to-trai-cay-154.html' => array('id' => 154, 'title' => 'Cách Làm Cách Làm Kem Sinh Tố Trái Cây Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách làm kem sinh tố trái cây chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem c...', 'h1' => 'Cách Làm Kem Sinh Tố Trái Cây'),
            '/day-pha-che-tra-sua-ngon/cach-lam-kem-tuoi-tra-sua-ngon-chuan-thuong-hieu-146.html' => array('id' => 146, 'title' => 'Cách Làm Cách Làm Kem Tươi Trà Sữa Ngon Chuẩn Thương Hiệu Chuẩn V...', 'description' => 'Hướng dẫn cách làm cách làm kem tươi trà sữa ngon chuẩn thương hiệu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Cách Làm Kem Tươi Trà Sữa Ngon Chuẩn Thương Hiệu'),
            '/day-pha-che-tra-sua-ngon/cach-lam-mon-banh-chocolate-tan-chay-151.html' => array('id' => 151, 'title' => 'Cách Làm Cách Làm Món Bánh Chocolate Tan Chảy Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm cách làm món bánh chocolate tan chảy chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Cách Làm Món Bánh Chocolate Tan Chảy'),
            '/day-pha-che-tra-sua-ngon/cach-lam-mut-bi-dao-trang-gion-ngon-ngay-tet-204.html' => array('id' => 204, 'title' => 'Cách Làm Cách Làm Mứt Bí Đao Thơm Ngon Đẹp Mắt Theo Công Thức của...', 'description' => 'Hướng dẫn cách làm cách làm mứt bí đao thơm ngon đẹp mắt theo công thức của cô ba bình dương chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hư...', 'h1' => 'Cách Làm Mứt Bí Đao Thơm Ngon Đẹp Mắt Theo Công Thức của Cô Ba Bình Dương'),
            '/day-pha-che-tra-sua-ngon/cach-lam-mut-dua-non-thom-ngon-beo-ngay-nham-nhi-ngay-tet-202.html' => array('id' => 202, 'title' => 'Cách Làm Cách Làm Mứt Dừa Non Thơm Ngon, Béo Ngậy Nhâm Nhi Ngày T...', 'description' => 'Hướng dẫn cách làm cách làm mứt dừa non thơm ngon, béo ngậy nhâm nhi ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu c...', 'h1' => 'Cách Làm Mứt Dừa Non Thơm Ngon, Béo Ngậy Nhâm Nhi Ngày Tết'),
            '/day-pha-che-tra-sua-ngon/cach-lam-nuoc-ep-ca-rot-tao-va-gung-su-ket-hop-dang-kinh-ngac-173.html' => array('id' => 173, 'title' => 'Cách Làm Cách Làm Nước Ép Cà Rốt, Táo và Gừng - Sự Kết Hợp Đáng K...', 'description' => 'Hướng dẫn cách làm cách làm nước ép cà rốt, táo và gừng - sự kết hợp đáng kinh ngạc chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tố...', 'h1' => 'Cách Làm Nước Ép Cà Rốt, Táo và Gừng - Sự Kết Hợp Đáng Kinh Ngạc'),
            '/day-pha-che-tra-sua-ngon/cach-lam-nuoc-ep-cu-cai-duong-duy-tri-suc-khoe-174.html' => array('id' => 174, 'title' => 'Cách Làm Cách Làm Nước Ép Củ Cải Đường - Duy Trì Sức Khoẻ Chuẩn V...', 'description' => 'Hướng dẫn cách làm cách làm nước ép củ cải đường - duy trì sức khoẻ chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Cách Làm Nước Ép Củ Cải Đường - Duy Trì Sức Khoẻ'),
            '/day-pha-che-tra-sua-ngon/cach-lam-nuoc-ep-tao-xanh-thuc-uong-mua-he-ly-tuong-172.html' => array('id' => 172, 'title' => 'Cách Làm Cách Làm Nước Ép Táo Xanh - Thức Uống Mùa Hè Lý Tưởng Ch...', 'description' => 'Hướng dẫn cách làm cách làm nước ép táo xanh - thức uống mùa hè lý tưởng chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Cách Làm Nước Ép Táo Xanh - Thức Uống Mùa Hè Lý Tưởng'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sinh-to-chanh-tuyet-57.html' => array('id' => 57, 'title' => 'Bí Quyết Pha Cách Làm Sinh Tố Chanh Tuyết Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm cách làm sinh tố chanh tuyết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem cô...', 'h1' => 'Cách Làm Sinh Tố Chanh Tuyết'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sinh-to-chuoi-tao-su-ket-hop-hoan-hao-171.html' => array('id' => 171, 'title' => 'Cách Làm Cách Làm Sinh Tố Chuối Táo - Sự Kết Hợp Hoàn Hảo Chuẩn V...', 'description' => 'Hướng dẫn cách làm cách làm sinh tố chuối táo - sự kết hợp hoàn hảo chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Cách Làm Sinh Tố Chuối Táo - Sự Kết Hợp Hoàn Hảo'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sinh-to-mix-trai-cay-chuan-khong-can-chinh-175.html' => array('id' => 175, 'title' => 'Cách Làm Cách Làm Sinh Tố Mix Trái Cây - Chuẩn Không Cần Chỉnh Ch...', 'description' => 'Hướng dẫn cách làm cách làm sinh tố mix trái cây - chuẩn không cần chỉnh chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Cách Làm Sinh Tố Mix Trái Cây - Chuẩn Không Cần Chỉnh'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sinh-to-tao-xanh-luu-ngot-149.html' => array('id' => 149, 'title' => 'Cách Làm Cách Làm Sinh Tố Táo Xanh - Lựu Ngọt Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm cách làm sinh tố táo xanh - lựu ngọt chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Cách Làm Sinh Tố Táo Xanh - Lựu Ngọt'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sua-chua-xoai-dong-lanh-150.html' => array('id' => 150, 'title' => 'Cách Làm Cách Làm Sữa Chua Xoài Đông Lạnh Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách làm sữa chua xoài đông lạnh chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xe...', 'h1' => 'Cách Làm Sữa Chua Xoài Đông Lạnh'),
            '/day-pha-che-tra-sua-ngon/cach-lam-sua-tuoi-tran-chau-duong-den-ngon-kho-cuong-123.html' => array('id' => 123, 'title' => 'Cách Làm Cách Làm Sữa Tươi Trân Châu Đường Đen Ngon Khó Cưỡng Chu...', 'description' => 'Hướng dẫn cách làm cách làm sữa tươi trân châu đường đen ngon khó cưỡng chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí...', 'h1' => 'Cách Làm Sữa Tươi Trân Châu Đường Đen Ngon Khó Cưỡng'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-sua-3-tang-ngon-la-hap-dan-61.html' => array('id' => 61, 'title' => 'Cách Làm Cách Làm Trà Sữa 3 Tầng Ngon Lạ Hấp Dẫn Chuẩn Vị [Công T...', 'description' => 'Hướng dẫn cách làm cách làm trà sữa 3 tầng ngon lạ hấp dẫn chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật l...', 'h1' => 'Cách Làm Trà Sữa 3 Tầng Ngon Lạ Hấp Dẫn'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-sua-ba-tuoc-earl-grey-don-gian-tai-nha-258.html' => array('id' => 258, 'title' => 'Cách Làm Cách Làm Trà Sữa Bá Tước Earl Grey Đơn Giản Tại Nhà Chuẩ...', 'description' => 'Hướng dẫn cách làm cách làm trà sữa bá tước earl grey đơn giản tại nhà chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ...', 'h1' => 'Cách Làm Trà Sữa Bá Tước Earl Grey Đơn Giản Tại Nhà'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-sua-khoai-lang-tim-chuan-thuong-hieu-155.html' => array('id' => 155, 'title' => 'Cách Làm Cách Làm Trà Sữa Khoai Lang Tím Chuẩn Thương Hiệu Chuẩn ...', 'description' => 'Hướng dẫn cách làm cách làm trà sữa khoai lang tím chuẩn thương hiệu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ng...', 'h1' => 'Cách Làm Trà Sữa Khoai Lang Tím Chuẩn Thương Hiệu'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-sua-tra-xanh-ngon-chuan-vi-255.html' => array('id' => 255, 'title' => 'Cách Làm Cách Làm Trà Sữa Trà Xanh Ngon Chuẩn Vị Chuẩn Vị [Công T...', 'description' => 'Hướng dẫn cách làm cách làm trà sữa trà xanh ngon chuẩn vị chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật l...', 'h1' => 'Cách Làm Trà Sữa Trà Xanh Ngon Chuẩn Vị'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-sua-uyen-uong-vi-ngon-kho-cuong-169.html' => array('id' => 169, 'title' => 'Cách Làm Cách Làm Trà Sữa Uyên Ương - Vị Ngon Khó Cưỡng Chuẩn Vị ...', 'description' => 'Hướng dẫn cách làm cách làm trà sữa uyên ương - vị ngon khó cưỡng chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyê...', 'h1' => 'Cách Làm Trà Sữa Uyên Ương - Vị Ngon Khó Cưỡng'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-xanh-xoai-latte-chuan-thuong-hieu-165.html' => array('id' => 165, 'title' => 'Cách Làm Cách Làm “trà Xanh Xoài LATTE” Chuẩn Thương Hiệu Chuẩn V...', 'description' => 'Hướng dẫn cách làm cách làm “trà xanh xoài latte” chuẩn thương hiệu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Cách Làm “trà Xanh Xoài LATTE” Chuẩn Thương Hiệu'),
            '/day-pha-che-tra-sua-ngon/cach-lam-tra-xoai-xoi-dau-heytea-152.html' => array('id' => 152, 'title' => 'Cách Làm Cách Làm Trà Xoài Xôi Dâu Heytea Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách làm trà xoài xôi dâu heytea chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xe...', 'h1' => 'Cách Làm Trà Xoài Xôi Dâu Heytea'),
            '/day-pha-che-tra-sua-ngon/cach-muoi-cu-kieu-trang-gion-ngon-dung-dieu-ngay-tet-203.html' => array('id' => 203, 'title' => 'Cách Làm Cách Muối Củ Kiệu Trắng Giòn, Ngon Đúng Điệu Ngày Tết Ch...', 'description' => 'Hướng dẫn cách làm cách muối củ kiệu trắng giòn, ngon đúng điệu ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Công Thức & Cách Pha Cách Muối Củ Kiệu Trắng Giòn, Ngon Đúng Điệu Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/cach-pha-che-cafe-da-xay-53.html' => array('id' => 53, 'title' => 'Bí Quyết Pha Cách Pha Chế Cafe Đá Xay Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm cách pha chế cafe đá xay chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem công t...', 'h1' => 'Cách Pha Chế Cafe Đá Xay'),
            '/day-pha-che-tra-sua-ngon/cach-pha-che-tra-sua-o-dau-ngon-46.html' => array('id' => 46, 'title' => 'Cách Làm Cách Pha Chế Trà Sữa Ở Đâu Ngon Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách pha chế trà sữa ở đâu ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem...', 'h1' => 'Cách Pha Chế Trà Sữa Ở Đâu Ngon'),
            '/day-pha-che-tra-sua-ngon/cach-pha-che-tra-sua-tran-chau-ngon-67.html' => array('id' => 67, 'title' => 'Cách Làm Cách Pha Chế Trà Sữa Trân Châu Ngon Chuẩn Vị [Công Thức ...', 'description' => 'Hướng dẫn cách làm cách pha chế trà sữa trân châu ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu....', 'h1' => 'Cách Pha Chế Trà Sữa Trân Châu Ngon'),
            '/day-pha-che-tra-sua-ngon/cach-pha-do-uong-giai-ruou-ngay-tet-don-gian-nhat-200.html' => array('id' => 200, 'title' => 'Cách Làm Cách Pha Đồ Uống Giải Rượu Ngày Tết Đơn Giản Nhất Chuẩn ...', 'description' => 'Hướng dẫn cách làm cách pha đồ uống giải rượu ngày tết đơn giản nhất chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ng...', 'h1' => 'Cách Pha Đồ Uống Giải Rượu Ngày Tết Đơn Giản Nhất'),
            '/day-pha-che-tra-sua-ngon/cach-pha-mot-shot-ca-phe-ngon-163.html' => array('id' => 163, 'title' => 'Cách Làm Cách Pha Một Shot Cà Phê Ngon Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách pha một shot cà phê ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem c...', 'h1' => 'Cách Pha Một Shot Cà Phê Ngon'),
            '/day-pha-che-tra-sua-ngon/cach-pha-tra-sua-ngon-mo-quan-66.html' => array('id' => 66, 'title' => 'Cách Làm Cách Pha Trà Sữa Ngon Mở Quán Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm cách pha trà sữa ngon mở quán chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem c...', 'h1' => 'Cách Pha Trà Sữa Ngon Mở Quán'),
            '/day-pha-che-tra-sua-ngon/cach-pha-tra-sua-oolong-ngon-nhu-thuong-hieu-254.html' => array('id' => 254, 'title' => 'Cách Làm Cách Pha Trà Sữa Oolong Ngon Như Thương Hiệu Chuẩn Vị [C...', 'description' => 'Hướng dẫn cách làm cách pha trà sữa oolong ngon như thương hiệu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên ...', 'h1' => 'Cách Pha Trà Sữa Oolong Ngon Như Thương Hiệu'),
            '/day-pha-che-tra-sua-ngon/cach-pha-tra-sua-tra-den-dam-da-huong-vi-256.html' => array('id' => 256, 'title' => 'Cách Làm Cách Pha Trà Sữa Trà Đen Đậm Đà Hương Vị Chuẩn Vị [Công ...', 'description' => 'Hướng dẫn cách làm cách pha trà sữa trà đen đậm đà hương vị chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật ...', 'h1' => 'Cách Pha Trà Sữa Trà Đen Đậm Đà Hương Vị'),
            '/day-pha-che-tra-sua-ngon/cach-phan-biet-cafe-that-va-cafe-gia-124.html' => array('id' => 124, 'title' => 'Cách Làm Cách Phân Biệt Cafe Thật và Cafe Giả Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm cách phân biệt cafe thật và cafe giả chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Công Thức & Cách Pha Cách Phân Biệt Cafe Thật và Cafe Giả Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/chieu-sinh-khoa-hoc-tra-thai-o-dau-49.html' => array('id' => 49, 'title' => 'Cách Làm Chiêu Sinh Khóa Học Trà Thái Ở Đâu Chuẩn Vị [Công Thức 2...', 'description' => 'Hướng dẫn cách làm chiêu sinh khóa học trà thái ở đâu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. ...', 'h1' => 'Công Thức & Cách Pha Chiêu Sinh Khóa Học Trà Thái Ở Đâu Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/cong-nghe-pha-tra-4-0-162.html' => array('id' => 162, 'title' => 'Bí Quyết Pha Công Nghệ Pha Trà 4.0 Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm công nghệ pha trà 4.0 chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem công thức...', 'h1' => 'Công Thức & Cách Pha Công Nghệ Pha Trà 4.0 Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/cong-thuc-cach-lam-tra-sua-nuong-ngon-chuan-nhat-228.html' => array('id' => 228, 'title' => 'Cách Làm Công Thức Cách Làm Trà Sữa Nướng Ngon Chuẩn Nhất Chuẩn V...', 'description' => 'Hướng dẫn cách làm công thức cách làm trà sữa nướng ngon chuẩn nhất chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ngu...', 'h1' => 'Công Thức Cách Làm Trà Sữa Nướng Ngon Chuẩn Nhất'),
            '/day-pha-che-tra-sua-ngon/dao-tao-pha-che-tron-goi-mo-quan-khac-biet-54.html' => array('id' => 54, 'title' => 'Cách Làm Đào Tạo Pha Chế Trọn Gói Mở Quán Khác Biệt Chuẩn Vị [Côn...', 'description' => 'Hướng dẫn cách làm đào tạo pha chế trọn gói mở quán khác biệt chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vậ...', 'h1' => 'Công Thức & Cách Pha Đào Tạo Pha Chế Trọn Gói Mở Quán Khác Biệt Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/day-pha-che-sinh-to-48.html' => array('id' => 48, 'title' => 'Bí Quyết Pha Dạy Pha Chế Sinh Tố Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm dạy pha chế sinh tố chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem công thức n...', 'h1' => 'Công Thức & Cách Pha Dạy Pha Chế Sinh Tố Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/day-pha-che-tra-sua-ngon-de-mo-quan-amp-hoc-cach-lam-chu-quan-tra-sua-cafe-sinh-to-kem-69.html' => array('id' => 69, 'title' => 'Cách Làm Dạy Pha Chế Trà Sữa Ngon để Mở Quán & Học Cách Làm Chủ Q...', 'description' => 'Hướng dẫn cách làm dạy pha chế trà sữa ngon để mở quán & học cách làm chủ quán trà sữa - cafe - sinh tố - kem chuẩn vị kinh doanh: Định lượng chính xác, kỹ t...', 'h1' => 'Dạy Pha Chế Trà Sữa Ngon để Mở Quán & Học Cách Làm Chủ Quán Trà Sữa - Cafe - Sinh Tố - Kem'),
            '/day-pha-che-tra-sua-ngon/day-pha-che-tra-sua-o-dau-uy-tin-45.html' => array('id' => 45, 'title' => 'Cách Làm Dạy Pha Chế Trà Sữa Ở Đâu Uy Tín Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm dạy pha chế trà sữa ở đâu uy tín chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xe...', 'h1' => 'Công Thức & Cách Pha Dạy Pha Chế Trà Sữa Ở Đâu Uy Tín Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/de-quan-cafe-luon-dong-khach-ban-can-phai-lam-gi-129.html' => array('id' => 129, 'title' => 'Cách Làm Để Quán Cafe Luôn Đông Khách, Bạn Cần Phải Làm Gì Chuẩn ...', 'description' => 'Hướng dẫn cách làm để quán cafe luôn đông khách, bạn cần phải làm gì chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ng...', 'h1' => 'Công Thức & Cách Pha Để Quán Cafe Luôn Đông Khách, Bạn Cần Phải Làm Gì Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/dung-cu-pha-tra-bang-da-lanh-doc-dao-230.html' => array('id' => 230, 'title' => 'Cách Làm Dụng Cụ Pha Trà Bằng Đá Lạnh Độc Đáo Chuẩn Vị [Công Thức...', 'description' => 'Hướng dẫn cách làm dụng cụ pha trà bằng đá lạnh độc đáo chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu...', 'h1' => 'Công Thức & Cách Pha Dụng Cụ Pha Trà Bằng Đá Lạnh Độc Đáo Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/goi-banh-tet-co-kho-nhu-ban-nghi-189.html' => array('id' => 189, 'title' => 'Cách Làm Học Cách Gói Bánh Tét Truyền Thống từ Công Thức của Cô B...', 'description' => 'Hướng dẫn cách làm học cách gói bánh tét truyền thống từ công thức của cô ba bình dương - vị ngon đậm chất miền nam chuẩn vị kinh doanh: Định lượng chính xác...', 'h1' => 'Học Cách Gói Bánh Tét Truyền Thống từ Công Thức của Cô Ba Bình Dương - Vị Ngon Đậm Chất Miền Nam'),
            '/day-pha-che-tra-sua-ngon/goi-y-mam-cung-chay-thinh-soan-ngay-tet-210.html' => array('id' => 210, 'title' => 'Cách Làm Chuẩn Bị Mâm Cúng Chay Thịnh Soạn Ngày Tết - Đừng Bỏ Qua...', 'description' => 'Hướng dẫn cách làm chuẩn bị mâm cúng chay thịnh soạn ngày tết - đừng bỏ qua 8 món sau đây chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương...', 'h1' => 'Công Thức & Cách Pha Chuẩn Bị Mâm Cúng Chay Thịnh Soạn Ngày Tết - Đừng Bỏ Qua 8 Món Sau Đây Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/goi-y-thuc-don-mam-com-ngay-tet-ngon-don-gian-199.html' => array('id' => 199, 'title' => 'Cách Làm Gợi Ý Thực Đơn Mâm Cơm Ngày Tết Ngon - Đơn Giản Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm gợi ý thực đơn mâm cơm ngày tết ngon - đơn giản chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Công Thức & Cách Pha Gợi Ý Thực Đơn Mâm Cơm Ngày Tết Ngon - Đơn Giản Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/hai-cach-lam-tra-sua-thao-moc-mang-lai-nhieu-loi-ich-suc-khoe-257.html' => array('id' => 257, 'title' => 'Cách Làm Hai Cách Làm Trà Sữa Thảo Mộc Mang Lại Nhiều Lợi Ích Sức...', 'description' => 'Hướng dẫn cách làm hai cách làm trà sữa thảo mộc mang lại nhiều lợi ích sức khỏe chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ư...', 'h1' => 'Hai Cách Làm Trà Sữa Thảo Mộc Mang Lại Nhiều Lợi Ích Sức Khỏe'),
            '/day-pha-che-tra-sua-ngon/hap-dan-voi-cach-lam-mut-ca-rot-ngon-bat-bai-ngay-tet-201.html' => array('id' => 201, 'title' => 'Cách Làm Hấp Dẫn với Cách Làm Mứt Cà Rốt Ngon Bất Bại Ngày Tết Ch...', 'description' => 'Hướng dẫn cách làm hấp dẫn với cách làm mứt cà rốt ngon bất bại ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Hấp Dẫn với Cách Làm Mứt Cà Rốt Ngon Bất Bại Ngày Tết'),
            '/day-pha-che-tra-sua-ngon/hoc-cach-de-mo-quan-tra-sua-thanh-cong-94.html' => array('id' => 94, 'title' => 'Cách Làm Học Cách để Mở Quán Trà Sữa Thành Công Chuẩn Vị [Công Th...', 'description' => 'Hướng dẫn cách làm học cách để mở quán trà sữa thành công chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật li...', 'h1' => 'Công Thức & Cách Pha Học Cách để Mở Quán Trà Sữa Thành Công Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/hoc-cach-goi-banh-chung-xum-vay-ngay-tet-190.html' => array('id' => 190, 'title' => 'Cách Làm Học Cách Gói Bánh Chưng – Xum Vầy Ngày Tết Chuẩn Vị [Côn...', 'description' => 'Hướng dẫn cách làm học cách gói bánh chưng – xum vầy ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vậ...', 'h1' => 'Công Thức & Cách Pha Học Cách Gói Bánh Chưng – Xum Vầy Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/hoc-pha-che-ruou-bartending-skill-course-50.html' => array('id' => 50, 'title' => 'Học Pha Chế Rượu Chuyên Nghiệp - Bartending Skill Course [2026]', 'description' => 'Khóa đào tạo kỹ năng pha chế rượu và cocktail Bartending chuyên nghiệp tại Passion Link: Nắm vững kỹ thuật lắc shaker, mixology và nghệ thuật quầy bar.', 'h1' => 'Khóa Học Pha Chế Rượu & Kỹ Năng Bartending Chuyên Nghiệp'),
            '/day-pha-che-tra-sua-ngon/huong-dan-cach-lam-tra-sua-nong-thuc-uong-tuyet-voi-cho-mua-dong-khong-lanh-145.html' => array('id' => 145, 'title' => 'Cách Làm Hướng Dẫn Cách Làm Trà Sữa Nóng - Thức Uống Tuyệt Vời ch...', 'description' => 'Hướng dẫn cách làm hướng dẫn cách làm trà sữa nóng - thức uống tuyệt vời cho mùa đông không lạnh chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậ...', 'h1' => 'Hướng Dẫn Cách Làm Trà Sữa Nóng - Thức Uống Tuyệt Vời cho Mùa Đông Không Lạnh'),
            '/day-pha-che-tra-sua-ngon/huong-dan-chon-la-dong-va-nguyen-lieu-ngon-de-goi-banh-chung-ngay-tet-187.html' => array('id' => 187, 'title' => 'Cách Làm Hướng Dẫn Chọn Lá Dong và Nguyên Liệu Ngon để Gói Bánh C...', 'description' => 'Hướng dẫn cách làm hướng dẫn chọn lá dong và nguyên liệu ngon để gói bánh chưng ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương ...', 'h1' => 'Công Thức & Cách Pha Hướng Dẫn Chọn Lá Dong và Nguyên Liệu Ngon để Gói Bánh Chưng Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/huong-dan-lam-nem-chay-gion-ngon-tron-vi-ngay-tet-193.html' => array('id' => 193, 'title' => 'Cách Làm Hướng Dẫn Làm Nem Chay Giòn Ngon Tròn Vị Ngày Tết Chuẩn ...', 'description' => 'Hướng dẫn cách làm hướng dẫn làm nem chay giòn ngon tròn vị ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí ng...', 'h1' => 'Công Thức & Cách Pha Hướng Dẫn Làm Nem Chay Giòn Ngon Tròn Vị Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/huong-dan-pha-che-thuc-uong-theo-yeu-cau-51.html' => array('id' => 51, 'title' => 'Cách Làm Hướng Dẫn Pha Chế Thức Uống Theo Yêu Cầu Chuẩn Vị [Công ...', 'description' => 'Hướng dẫn cách làm hướng dẫn pha chế thức uống theo yêu cầu chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật ...', 'h1' => 'Công Thức & Cách Pha Hướng Dẫn Pha Chế Thức Uống Theo Yêu Cầu Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/huong-dan-trang-tri-mam-ngu-qua-ngay-tet-dep-don-gian-184.html' => array('id' => 184, 'title' => 'Cách Làm Hướng Dẫn Trang Trí Mâm Ngũ Quả Ngày Tết Đẹp Đơn Giản Ch...', 'description' => 'Hướng dẫn cách làm hướng dẫn trang trí mâm ngũ quả ngày tết đẹp đơn giản chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Công Thức & Cách Pha Hướng Dẫn Trang Trí Mâm Ngũ Quả Ngày Tết Đẹp Đơn Giản Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/khoa-hoc-thuc-uong-mo-quan-56.html' => array('id' => 56, 'title' => 'Bí Quyết Pha Khóa Học Thức Uống Mở Quán Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm khóa học thức uống mở quán chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem công...', 'h1' => 'Công Thức & Cách Pha Khóa Học Thức Uống Mở Quán Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/kinh-nghiem-lua-chon-thuc-pham-an-toan-trong-dip-tet-nguyen-dan-212.html' => array('id' => 212, 'title' => 'Cách Làm Kinh Nghiệm Lựa Chọn Thực Phẩm An Toàn trong Dịp Tết Ngu...', 'description' => 'Hướng dẫn cách làm kinh nghiệm lựa chọn thực phẩm an toàn trong dịp tết nguyên đán chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối...', 'h1' => 'Công Thức & Cách Pha Kinh Nghiệm Lựa Chọn Thực Phẩm An Toàn trong Dịp Tết Nguyên Đán Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/lam-gi-cho-ngay-khai-truong-dong-khach-166.html' => array('id' => 166, 'title' => 'Cách Làm Làm Gì cho Ngày Khai Trương Đông Khách Chuẩn Vị [Công Th...', 'description' => 'Hướng dẫn cách làm làm gì cho ngày khai trương đông khách chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật li...', 'h1' => 'Công Thức & Cách Pha Làm Gì cho Ngày Khai Trương Đông Khách Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/lam-the-nao-de-biet-duoc-bi-mat-thanh-cong-167.html' => array('id' => 167, 'title' => 'Cách Làm Làm Thế Nào để Biết Được Bí Mật Thành Công Chuẩn Vị [Côn...', 'description' => 'Hướng dẫn cách làm làm thế nào để biết được bí mật thành công chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vậ...', 'h1' => 'Công Thức & Cách Pha Làm Thế Nào để Biết Được Bí Mật Thành Công Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/meo-bao-quan-banh-chung-sau-tet-den-10-ngay-186.html' => array('id' => 186, 'title' => 'Cách Làm Mẹo Bảo Quản Bánh Chưng Sau Tết Đến 10 Ngày Chuẩn Vị [Cô...', 'description' => 'Hướng dẫn cách làm mẹo bảo quản bánh chưng sau tết đến 10 ngày chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên v...', 'h1' => 'Công Thức & Cách Pha Mẹo Bảo Quản Bánh Chưng Sau Tết Đến 10 Ngày Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/mo-quan-kinh-doanh-tra-sua-can-bao-nhieu-von-52.html' => array('id' => 52, 'title' => 'Cách Làm Mở Quán Kinh Doanh Trà Sữa Cần Bao Nhiêu Vốn Chuẩn Vị [C...', 'description' => 'Hướng dẫn cách làm mở quán kinh doanh trà sữa cần bao nhiêu vốn chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên ...', 'h1' => 'Công Thức & Cách Pha Mở Quán Kinh Doanh Trà Sữa Cần Bao Nhiêu Vốn Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/nghe-thuat-pha-che-tra-sua-55.html' => array('id' => 55, 'title' => 'Bí Quyết Pha Nghệ Thuật Pha Chế Trà Sữa Thơm Ngon Hút Khách [2026]', 'description' => 'Hướng dẫn cách làm nghệ thuật pha chế trà sữa chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. Xem công...', 'h1' => 'Công Thức & Cách Pha Nghệ Thuật Pha Chế Trà Sữa Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/nhung-dieu-cam-ki-khi-bay-mam-ngu-qua-ngay-tet-198.html' => array('id' => 198, 'title' => 'Cách Làm Những Điều Cấm Kị Khi Bày Mâm Ngũ Quả Ngày Tết Chuẩn Vị ...', 'description' => 'Hướng dẫn cách làm những điều cấm kị khi bày mâm ngũ quả ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyê...', 'h1' => 'Công Thức & Cách Pha Những Điều Cấm Kị Khi Bày Mâm Ngũ Quả Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/nhung-dieu-cam-ky-trong-ngay-ong-cong-ong-tao-211.html' => array('id' => 211, 'title' => 'Cách Làm Những Điều Cấm Kỵ trong Ngày Ông Công Ông Táo Chuẩn Vị [...', 'description' => 'Hướng dẫn cách làm những điều cấm kỵ trong ngày ông công ông táo chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên...', 'h1' => 'Công Thức & Cách Pha Những Điều Cấm Kỵ trong Ngày Ông Công Ông Táo Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/nhung-dieu-can-luu-y-khi-mo-quan-tra-sua-97.html' => array('id' => 97, 'title' => 'Cách Làm Những Điều Cần Lưu Ý Khi Mở Quán Trà Sữa Chuẩn Vị [Công ...', 'description' => 'Hướng dẫn cách làm những điều cần lưu ý khi mở quán trà sữa chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật ...', 'h1' => 'Công Thức & Cách Pha Những Điều Cần Lưu Ý Khi Mở Quán Trà Sữa Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/nhung-loi-ich-tuyet-voi-cua-matcha-ma-ban-khong-the-ngo-toi-134.html' => array('id' => 134, 'title' => 'Cách Làm Những Lợi Ích Tuyệt Vời của Matcha Mà Bạn Không Thể Ngờ ...', 'description' => 'Hướng dẫn cách làm những lợi ích tuyệt vời của matcha mà bạn không thể ngờ tới chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ...', 'h1' => 'Công Thức & Cách Pha Những Lợi Ích Tuyệt Vời của Matcha Mà Bạn Không Thể Ngờ Tới Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/soda-mix-trai-cay-tuoi-giai-khat-giam-can-tuyet-dinh-168.html' => array('id' => 168, 'title' => 'Cách Làm Soda Mix Trái Cây Tươi - Giải Khát Giảm Cân Tuyệt Đỉnh C...', 'description' => 'Hướng dẫn cách làm soda mix trái cây tươi - giải khát giảm cân tuyệt đỉnh chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi p...', 'h1' => 'Công Thức & Cách Pha Soda Mix Trái Cây Tươi - Giải Khát Giảm Cân Tuyệt Đỉnh Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/su-khac-biet-cua-cac-loai-cot-tra-nhat-dinh-phai-biet-132.html' => array('id' => 132, 'title' => 'Cách Làm Sự Khác Biệt của Các Loại Cốt Trà Nhất Định Phải Biết Ch...', 'description' => 'Hướng dẫn cách làm sự khác biệt của các loại cốt trà nhất định phải biết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi ph...', 'h1' => 'Công Thức & Cách Pha Sự Khác Biệt của Các Loại Cốt Trà Nhất Định Phải Biết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/su-khac-biet-cuc-thu-vi-giua-tet-co-truyen-o-mien-bac-va-mien-nam-188.html' => array('id' => 188, 'title' => 'Cách Làm Sự Khác Biệt Cực Thú Vị Giữa Tết Cổ Truyền Ở Miền Bắc và...', 'description' => 'Hướng dẫn cách làm sự khác biệt cực thú vị giữa tết cổ truyền ở miền bắc và miền nam chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và t...', 'h1' => 'Công Thức & Cách Pha Sự Khác Biệt Cực Thú Vị Giữa Tết Cổ Truyền Ở Miền Bắc và Miền Nam Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/thuc-don-mam-chay-don-gian-de-lam-cung-ngay-ram-thang-gieng-213.html' => array('id' => 213, 'title' => 'Cách Làm Thực Đơn Mâm Chay Đơn Giản Dễ Làm Cúng Ngày Rằm Tháng Gi...', 'description' => 'Hướng dẫn cách làm thực đơn mâm chay đơn giản dễ làm cúng ngày rằm tháng giêng chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ...', 'h1' => 'Công Thức & Cách Pha Thực Đơn Mâm Chay Đơn Giản Dễ Làm Cúng Ngày Rằm Tháng Giêng Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/thuc-don-thanh-loc-co-the-sau-tet-216.html' => array('id' => 216, 'title' => 'Cách Làm Thực Đơn Thanh Lọc Cơ Thể Sau Tết Chuẩn Vị [Công Thức 2026]', 'description' => 'Hướng dẫn cách làm thực đơn thanh lọc cơ thể sau tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật liệu. X...', 'h1' => 'Công Thức & Cách Pha Thực Đơn Thanh Lọc Cơ Thể Sau Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/top-10-thuong-hieu-ca-phe-tot-nhat-the-gioi-158.html' => array('id' => 158, 'title' => 'Cách Làm Top 10 Thương Hiệu Cà Phê Tốt Nhất Thế Giới Chuẩn Vị [Cô...', 'description' => 'Hướng dẫn cách làm top 10 thương hiệu cà phê tốt nhất thế giới chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên v...', 'h1' => 'Công Thức & Cách Pha Top 10 Thương Hiệu Cà Phê Tốt Nhất Thế Giới Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/top-8-thuc-pham-thanh-nhiet-giai-doc-co-the-sau-ngay-tet-214.html' => array('id' => 214, 'title' => 'Cách Làm Top 8 Thực Phẩm Thanh Nhiệt, Giải Độc Cơ Thể Sau Ngày Tế...', 'description' => 'Hướng dẫn cách làm top 8 thực phẩm thanh nhiệt, giải độc cơ thể sau ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ch...', 'h1' => 'Công Thức & Cách Pha Top 8 Thực Phẩm Thanh Nhiệt, Giải Độc Cơ Thể Sau Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/top-do-uong-thanh-nhiet-giai-doc-nen-su-dung-trong-ngay-tet-197.html' => array('id' => 197, 'title' => 'Cách Làm Top Đồ Uống Thanh Nhiệt Giải Độc Nên Sử Dụng trong Ngày ...', 'description' => 'Hướng dẫn cách làm top đồ uống thanh nhiệt giải độc nên sử dụng trong ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ...', 'h1' => 'Công Thức & Cách Pha Top Đồ Uống Thanh Nhiệt Giải Độc Nên Sử Dụng trong Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/tra-sua-khoai-lang-tim-vi-ngon-ngat-ngay-147.html' => array('id' => 147, 'title' => 'Cách Làm Trà Sữa Khoai Lang Tím – Vị Ngon Ngất Ngây Chuẩn Vị [Côn...', 'description' => 'Hướng dẫn cách làm trà sữa khoai lang tím – vị ngon ngất ngây chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vậ...', 'h1' => 'Công Thức & Cách Pha Trà Sữa Khoai Lang Tím – Vị Ngon Ngất Ngây Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/tran-chau-hoa-qua-rau-cu-tot-cho-suc-khoe-122.html' => array('id' => 122, 'title' => 'Cách Làm Trân Châu Hoa Quả Rau Củ Tốt cho Sức Khoẻ Chuẩn Vị [Công...', 'description' => 'Hướng dẫn cách làm trân châu hoa quả rau củ tốt cho sức khoẻ chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguyên vật...', 'h1' => 'Công Thức & Cách Pha Trân Châu Hoa Quả Rau Củ Tốt cho Sức Khoẻ Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/trang/1' => array('id' => 0, 'title' => 'Cách Làm Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm bí quyết hay - tin tức day pha chế trà sữa ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon'),
            '/day-pha-che-tra-sua-ngon/trang/2' => array('id' => 0, 'title' => 'Cách Làm Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm bí quyết hay - tin tức day pha chế trà sữa ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon'),
            '/day-pha-che-tra-sua-ngon/trang/3' => array('id' => 0, 'title' => 'Cách Làm Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm bí quyết hay - tin tức day pha chế trà sữa ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon'),
            '/day-pha-che-tra-sua-ngon/trang/4' => array('id' => 0, 'title' => 'Cách Làm Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm bí quyết hay - tin tức day pha chế trà sữa ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon'),
            '/day-pha-che-tra-sua-ngon/trang/5' => array('id' => 0, 'title' => 'Cách Làm Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon Chuẩn Vị...', 'description' => 'Hướng dẫn cách làm bí quyết hay - tin tức day pha chế trà sữa ngon chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí nguy...', 'h1' => 'Bí Quyết Hay - Tin Tức Day Pha Chế Trà Sữa Ngon'),
            '/day-pha-che-tra-sua-ngon/y-nghia-cac-loai-qua-dem-tai-loc-trong-mam-ngu-qua-ngay-tet-195.html' => array('id' => 195, 'title' => 'Cách Làm Ý Nghĩa Các Loại Quả Đem Tài Lộc trong Mâm Ngũ Quả Ngày ...', 'description' => 'Hướng dẫn cách làm ý nghĩa các loại quả đem tài lộc trong mâm ngũ quả ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu ...', 'h1' => 'Công Thức & Cách Pha Ý Nghĩa Các Loại Quả Đem Tài Lộc trong Mâm Ngũ Quả Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/day-pha-che-tra-sua-ngon/y-nghia-dac-trung-cua-7-loai-mut-quen-thuoc-ngay-tet-191.html' => array('id' => 191, 'title' => 'Cách Làm Ý Nghĩa Đặc Trưng của 7 Loại Mứt Quen Thuộc Ngày Tết Chu...', 'description' => 'Hướng dẫn cách làm ý nghĩa đặc trưng của 7 loại mứt quen thuộc ngày tết chuẩn vị kinh doanh: Định lượng chính xác, kỹ thuật ủ trà đậm hương và tối ưu chi phí...', 'h1' => 'Công Thức & Cách Pha Ý Nghĩa Đặc Trưng của 7 Loại Mứt Quen Thuộc Ngày Tết Chuẩn Vị Kinh Doanh'),
            '/tin-tuc/8-loai-tra-thao-moc-tot-cho-suc-khoe-nen-uong-moi-ngay-133.html' => array('id' => 133, 'title' => '8 Loại Trà Thảo Mộc Tốt cho Sức Khỏe Nên Uống Mỗi Ngày: Xu Hướng ...', 'description' => 'Cập nhật thông tin chuyên sâu về 8 loại trà thảo mộc tốt cho sức khỏe nên uống mỗi ngày: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh do...', 'h1' => '8 Loại Trà Thảo Mộc Tốt cho Sức Khỏe Nên Uống Mỗi Ngày - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/an-vat-tra-sua-banh-mi-chao-81.html' => array('id' => 81, 'title' => 'Ăn Vặt Trà Sữa - Bánh Mì Chảo - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về ăn vặt trà sữa - bánh mì chảo: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem ngay!', 'h1' => 'Ăn Vặt Trà Sữa - Bánh Mì Chảo - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-banh-nuong-thom-lung-naan-an-do-85.html' => array('id' => 85, 'title' => 'Cách Làm Bánh Nướng Thơm Lừng Naan Ấn Độ: Xu Hướng & Phân Tích Ch...', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm bánh nướng thơm lừng naan ấn độ: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ qu...', 'h1' => 'Cách Làm Bánh Nướng Thơm Lừng Naan Ấn Độ - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-banh-sua-tuoi-chien-gion-83.html' => array('id' => 83, 'title' => 'Cách Làm Bánh Sữa Tươi Chiên Giòn - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm bánh sữa tươi chiên giòn: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem...', 'h1' => 'Cách Làm Bánh Sữa Tươi Chiên Giòn - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-da-xay-kem-ngon-smoothies-kem-71.html' => array('id' => 71, 'title' => 'Cách Làm Đá Xay Kem Ngon, SMOOTHIES Kem: Xu Hướng & Phân Tích Chu...', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm đá xay kem ngon, smoothies kem: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quá...', 'h1' => 'Cách Làm Đá Xay Kem Ngon, SMOOTHIES Kem - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-kem-dua-ngon-82.html' => array('id' => 82, 'title' => 'Cách Làm Kem Dừa Ngon - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm kem dừa ngon: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem ngay!', 'h1' => 'Cách Làm Kem Dừa Ngon - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-sinh-to-rau-ma-dau-xanh-tot-cho-suc-khoe-92.html' => array('id' => 92, 'title' => 'Cách Làm Sinh Tố Rau Má Đậu Xanh Tốt cho Sức Khỏe: Xu Hướng & Phâ...', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm sinh tố rau má đậu xanh tốt cho sức khỏe: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh c...', 'h1' => 'Cách Làm Sinh Tố Rau Má Đậu Xanh Tốt cho Sức Khỏe - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-lam-thach-cu-nang-86.html' => array('id' => 86, 'title' => 'Cách Làm Thạch Củ Năng - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về cách làm thạch củ năng: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem ngay!', 'h1' => 'Cách Làm Thạch Củ Năng - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-pha-sua-tuoi-mia-tra-sua-mia-hut-hon-gioi-tre-225.html' => array('id' => 225, 'title' => 'Cách Pha Sữa Tươi Mía - Trà Sữa Mía “hút Hồn” Giới Trẻ: Xu Hướng ...', 'description' => 'Cập nhật thông tin chuyên sâu về cách pha sữa tươi mía - trà sữa mía “hút hồn” giới trẻ: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh do...', 'h1' => 'Cách Pha Sữa Tươi Mía - Trà Sữa Mía “hút Hồn” Giới Trẻ - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/cach-pha-tra-sua-68.html' => array('id' => 68, 'title' => 'Cách Pha Trà Sữa - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về cách pha trà sữa: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem ngay!', 'h1' => 'Cách Pha Trà Sữa - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/diem-danh-7-loai-tra-noi-tieng-nhat-the-gioi-125.html' => array('id' => 125, 'title' => 'Điểm Danh 7 Loại Trà Nổi Tiếng Nhất Thế Giới: Xu Hướng & Phân Tíc...', 'description' => 'Cập nhật thông tin chuyên sâu về điểm danh 7 loại trà nổi tiếng nhất thế giới: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho ch...', 'h1' => 'Điểm Danh 7 Loại Trà Nổi Tiếng Nhất Thế Giới - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/giai-nhiet-mua-he-voi-5-do-uong-sieu-hot-127.html' => array('id' => 127, 'title' => 'Giải Nhiệt Mùa Hè với 5 Đồ Uống Siêu Hot: Xu Hướng & Phân Tích Ch...', 'description' => 'Cập nhật thông tin chuyên sâu về giải nhiệt mùa hè với 5 đồ uống siêu hot: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ qu...', 'h1' => 'Giải Nhiệt Mùa Hè với 5 Đồ Uống Siêu Hot - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/hoc-pha-che-tra-sua-ngon-chuyen-nghiep-rau-cu-trai-cay-112.html' => array('id' => 112, 'title' => 'Học Pha Chế Trà Sữa Ngon Chuyên Nghiệp Rau Củ Trái Cây: Xu Hướng ...', 'description' => 'Cập nhật thông tin chuyên sâu về học pha chế trà sữa ngon chuyên nghiệp rau củ trái cây: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh do...', 'h1' => 'Học Pha Chế Trà Sữa Ngon Chuyên Nghiệp Rau Củ Trái Cây - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/huong-dan-pha-tra-sua-ngon-88.html' => array('id' => 88, 'title' => 'Hướng Dẫn Pha Trà Sữa Ngon - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về hướng dẫn pha trà sữa ngon: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem ngay!', 'h1' => 'Hướng Dẫn Pha Trà Sữa Ngon - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/khoa-hoc-pha-che-tra-sua-ngon-cao-cap-111.html' => array('id' => 111, 'title' => 'Khóa Học Pha Chế Trà Sữa Ngon Cao Cấp: Xu Hướng & Phân Tích Chuyê...', 'description' => 'Cập nhật thông tin chuyên sâu về khóa học pha chế trà sữa ngon cao cấp: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán....', 'h1' => 'Khóa Học Pha Chế Trà Sữa Ngon Cao Cấp - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/khoa-hoc-pha-che-tra-sua-ngon-mon-moi-mien-phi-84.html' => array('id' => 84, 'title' => 'Khóa Học Pha Chế Trà Sữa Ngon - Món Mới Miễn Phí: Xu Hướng & Phân...', 'description' => 'Cập nhật thông tin chuyên sâu về khóa học pha chế trà sữa ngon - món mới miễn phí: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh ch...', 'h1' => 'Khóa Học Pha Chế Trà Sữa Ngon - Món Mới Miễn Phí - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/may-in-hinh-len-tra-sua-va-ca-phe-vtv1-xu-huong-moi-2019-221.html' => array('id' => 221, 'title' => 'Máy In Hình Lên Trà Sữa và Cà Phê VTV1 Xu Hướng Mới 2019: Xu Hướn...', 'description' => 'Cập nhật thông tin chuyên sâu về máy in hình lên trà sữa và cà phê vtv1 xu hướng mới 2019: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh ...', 'h1' => 'Máy In Hình Lên Trà Sữa và Cà Phê VTV1 Xu Hướng Mới 2019 - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/mo-hinh-quan-tra-sua-kumanthong-222.html' => array('id' => 222, 'title' => 'Mô Hình Quán Trà Sữa Kumanthong - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về mô hình quán trà sữa kumanthong: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xem n...', 'h1' => 'Mô Hình Quán Trà Sữa Kumanthong - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/nhung-mon-an-vat-ngon-nhat-sai-gon-70.html' => array('id' => 70, 'title' => 'Những Món Ăn Vặt Ngon Nhất Sài Gòn - Xu Hướng Thị Trường F&B [2026]', 'description' => 'Cập nhật thông tin chuyên sâu về những món ăn vặt ngon nhất sài gòn: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ quán. Xe...', 'h1' => 'Những Món Ăn Vặt Ngon Nhất Sài Gòn - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/nua-tan-hoa-chat-khong-ro-nguon-goc-dung-san-xuat-siro-65.html' => array('id' => 65, 'title' => 'Nửa Tấn Hóa Chất Không Rõ Nguồn Gốc Dùng Sản Xuất Siro: Xu Hướng ...', 'description' => 'Cập nhật thông tin chuyên sâu về nửa tấn hóa chất không rõ nguồn gốc dùng sản xuất siro: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh do...', 'h1' => 'Nửa Tấn Hóa Chất Không Rõ Nguồn Gốc Dùng Sản Xuất Siro - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/san-xuat-giay-chong-tham-nuoc-tu-ba-ca-phe-va-rac-thai-nhua-san-pham-starup-cua-2-thanh-nien-viet-nam-244.html' => array('id' => 244, 'title' => 'Sản Xuất Giày Chống Thấm Nước từ Bã Cà Phê và Rác Thải Nhựa – Sản...', 'description' => 'Cập nhật thông tin chuyên sâu về sản xuất giày chống thấm nước từ bã cà phê và rác thải nhựa – sản phẩm starup của 2 thanh niên việt nam: Phân tích xu hướng ...', 'h1' => 'Sản Xuất Giày Chống Thấm Nước từ Bã Cà Phê và Rác Thải Nhựa – Sản Phẩm Starup của 2 Thanh Niên Việt Nam - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/trang/1' => array('id' => 0, 'title' => 'Tin Tức - Tin Tức Dạy Học Cách Pha Chế Ngon: Xu Hướng & Phân Tích...', 'description' => 'Cập nhật thông tin chuyên sâu về tin tức - tin tức dạy học cách pha chế ngon: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ...', 'h1' => 'Tin Tức - Tin Tức Dạy Học Cách Pha Chế Ngon - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/trang/2' => array('id' => 0, 'title' => 'Tin Tức - Tin Tức Dạy Học Cách Pha Chế Ngon: Xu Hướng & Phân Tích...', 'description' => 'Cập nhật thông tin chuyên sâu về tin tức - tin tức dạy học cách pha chế ngon: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh cho chủ...', 'h1' => 'Tin Tức - Tin Tức Dạy Học Cách Pha Chế Ngon - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/tin-tuc/van-hoa-uong-cafe-tai-cac-quoc-gia-tren-the-gioi-148.html' => array('id' => 148, 'title' => 'Văn Hóa Uống Cafe Tại Các Quốc Gia Trên Thế Giới: Xu Hướng & Phân...', 'description' => 'Cập nhật thông tin chuyên sâu về văn hóa uống cafe tại các quốc gia trên thế giới: Phân tích xu hướng đồ uống mới, thị trường F&B và chiến lược kinh doanh ch...', 'h1' => 'Văn Hóa Uống Cafe Tại Các Quốc Gia Trên Thế Giới - Phân Tích & Dự Báo Xu Hướng Thị Trường F&B'),
            '/cac-khoa-hoc/day-pha-che-tra-sua-tran-chau-34.html' => array('id' => 34, 'title' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu, Trà Thái [Menu 2026]', 'description' => 'Khóa học dạy pha chế trà sữa trân châu, trà Thái chuẩn vị mở quán tại Passion Link: 100% thực hành, hướng dẫn ủ trà đậm vị và tính cost giá vốn.', 'h1' => 'Khóa Học Dạy Pha Chế Trà Sữa Trân Châu & Trà Thái Ngon Chuẩn Vị Mở Quán'),
            '/hoc-pha-che-online.html' => array('id' => 0, 'title' => 'Khóa Học Pha Chế Online Từ Xa - Học Bí Quyết Mở Quán [2026]', 'description' => 'Khóa học pha chế online từ xa cùng chuyên gia Passion Link: Video quay sắc nét từng thao tác, công thức chuẩn định lượng, hỗ trợ 1 kèm 1 trọn đời.', 'h1' => 'Khóa Học Pha Chế Online Từ Xa - Đào Tạo Mở Quán Thực Chiến Passion Link'),
            '/lich-khai-giang/du-kien-ngay-khai-giang-pha-che-tai-da-nang-40.html' => array('id' => 40, 'title' => 'Lịch Khai Giảng Khóa Học Pha Chế Tại Đà Nẵng [Tháng Này]', 'description' => 'Lịch khai giảng các lớp học pha chế trà sữa, cà phê barista tại chi nhánh Passion Link Đà Nẵng. Đăng ký sớm nhận ngay ưu đãi học phí!', 'h1' => 'Lịch Khai Giảng Lớp Học Pha Chế Đồ Uống Mở Quán Tại Đà Nẵng'),
            '/lich-khai-giang/khai-giang-khoa-hoc-pha-che-tai-tphcm-38.html' => array('id' => 38, 'title' => 'Lịch Khai Giảng Khóa Học Pha Chế Tại TP.HCM [Tháng Này]', 'description' => 'Cập nhật lịch khai giảng lớp học pha chế trà sữa, barista tại TP.HCM (Quận 10, Phú Nhuận). Thực hành 100% trên quầy bar chuyên nghiệp.', 'h1' => 'Lịch Khai Giảng Khóa Học Pha Chế Mở Quán Tại TP.HCM Mới Nhất'),
            '/lich-khai-giang/lich-khai-giang-cac-khoa-hoc-pha-che-tai-can-tho-138.html' => array('id' => 138, 'title' => 'Lịch Khai Giảng Khóa Học Pha Chế Tại Cần Thơ [Tháng Này]', 'description' => 'Thông tin lịch khai giảng các khóa học pha chế trà sữa, cà phê, trà trái cây tại chi nhánh Passion Link Cần Thơ. Ưu đãi hấp dẫn khi đăng ký ngay!', 'h1' => 'Lịch Khai Giảng Các Khóa Học Pha Chế Mở Quán Tại Cần Thơ'),
            '/lich-khai-giang/lich-khai-giang-cac-khoa-hoc-pha-che-tai-ha-noi-39.html' => array('id' => 39, 'title' => 'Lịch Khai Giảng Khóa Học Pha Chế Tại Hà Nội [Tháng Này]', 'description' => 'Lịch khai giảng lớp học pha chế trà sữa, barista mở quán tại Passion Link Hà Nội. Cam kết học đến khi thuần thục, hỗ trợ trọn đời.', 'h1' => 'Lịch Khai Giảng Các Khóa Học Dạy Pha Chế Mở Quán Tại Hà Nội'),
            '/lich-khai-giang/nhan-dao-tao-pha-che-tai-quan-huong-dan-set-up-quan-41.html' => array('id' => 41, 'title' => 'Đào Tạo Pha Chế Tại Quán & Dịch Vụ Setup Quầy Bar Trọn Gói [2026]', 'description' => 'Passion Link nhận đào tạo pha chế trực tiếp tại quán và cố vấn setup quầy bar, lên menu độc quyền chuẩn phong cách cho chủ quán toàn quốc.', 'h1' => 'Dịch Vụ Đào Tạo Pha Chế Trực Tiếp Tại Quán & Hướng Dẫn Setup Quán F&B'),
            '/passion-link-lich-su-phat-trien.html' => array('id' => 0, 'title' => 'Lịch Sử Phát Triển Passion Link: 17+ Năm Tiên Phong Đào Tạo Pha Chế', 'description' => 'Hành trình hơn 17 năm tiên phong đào tạo pha chế đồ uống mở quán của Passion Link: Sứ mệnh nâng tầm chất lượng đồ uống Việt Nam và kiến tạo chủ quán thành công.', 'h1' => 'Lịch Sử Hình Thành & Sứ Mệnh Tiên Phong Đào Tạo F&B Passion Link'),
            '/thu-vien.html' => array('id' => 0, 'title' => 'Thư Viện Hình Ảnh & Hoạt Động Lớp Học | Passion Link', 'description' => 'Thư viện hình ảnh thực tế các lớp học pha chế, khoảnh khắc học viên thực hành quầy bar và không khí khai trương quán của học viên Passion Link.', 'h1' => 'Thư Viện Hình Ảnh Thực Tế Lớp Học Pha Chế & Quán Học Viên Passion Link'),
            '/tin-tuc.html' => array('id' => 0, 'title' => 'Tin Tức Sự Kiện & Xu Hướng F&B Mới Nhất [2026] | Passion Link', 'description' => 'Chuyên mục tin tức F&B Passion Link: Cập nhật xu hướng đồ uống hot trend, sự kiện khai giảng, bí quyết vận hành và câu chuyện khởi nghiệp quán.', 'h1' => 'Tin Tức Sự Kiện F&B & Cẩm Nang Kinh Nghiệm Khởi Nghiệp Đồ Uống'),
            '/cac-khoa-hoc-day-pha-che/day-pha-che-tra-sua-khoa-hoc-tra-sua-chuan-vi-tron-khoa-menu-ngon-72.html' => array('id' => 72, 'title' => 'Khóa Học Dạy Pha Chế Mở Quán Trà Sữa Chuẩn Vị Trọn Khóa [Menu 2026]', 'description' => 'Khóa học dạy pha chế mở quán trà sữa trọn khóa menu ngon chuẩn vị thực chiến tại Passion Link: 100% thực hành, hỗ trợ lên menu, tính cost giá vốn và đồng hành mở quán.', 'h1' => 'Khóa Học Dạy Pha Chế Mở Quán Trà Sữa Chuẩn Vị Trọn Khóa Menu Ngon'),
        );
    }

    if (empty($req_uri)) {
        return isset($seo_map_cache['/']) ? $seo_map_cache['/'] : null;
    }

    // Strip query strings and clean path
    $path = parse_url($req_uri, PHP_URL_PATH);
    $path = '/' . ltrim($path, '/');

    // 1. Direct path lookup
    if (isset($seo_map_cache[$path])) {
        return $seo_map_cache[$path];
    }

    // 2. Trailing slash normalization
    $rpath = rtrim($path, '/');
    if ($rpath !== '' && isset($seo_map_cache[$rpath])) {
        return $seo_map_cache[$rpath];
    }
    if ($path !== '/' && isset($seo_map_cache[$path . '/'])) {
        return $seo_map_cache[$path . '/'];
    }

    // 3. Match with .html extension
    if (substr($path, -5) !== '.html' && isset($seo_map_cache[$path . '.html'])) {
        return $seo_map_cache[$path . '.html'];
    }

    // 4. Lookup by news_id if provided
    if ($news_id > 0) {
        foreach ($seo_map_cache as $item) {
            if ($item["id"] === (int)$news_id) {
                return $item;
            }
        }
    }

    // 5. Extract id from path if ending in -{id}.html
    if (preg_match('/-([0-9]+)\.html$/', $path, $pm)) {
        $extracted_id = (int)$pm[1];
        foreach ($seo_map_cache as $item) {
            if ($item["id"] === $extracted_id) {
                return $item;
            }
        }
    }

    return null;
}
?>